-- Cindra runtime driver (§15 items 2-3 worldgen + items 7-9 power).
--
-- Hooks every Cindra periodic system to the live game:
--   * worldgen track: the tile-based lethal-edge damage sweep (lava/deep-ice
--     tiles burn everything on them, player + machines) and the ambient thermal
--     grade, a cosmetic position-driven screen hue wash sharing that tick (ci-nw0). The
--     nightside now freezes NATIVELY (§ freeze, ci-bvk): the planet flag
--     `entities_require_heating` + a worldgen line of invisible lava-heat emitters
--     (scripts/freeze-emitters.lua), placed on_chunk_generated -- this REPLACES the
--     old scripted building-heat cold-damage sweep. The RIBBON ITSELF (finite width,
--     noise tile bands, banded resources, finite rocks) is generated by the MAP-GEN.
--   * cosmetic track: the icy-side SNOWFALL (ci-mk5y, scripts/snowfall.lua) -- a drifting
--     per-player flake field drawn over the frozen half of the ribbon only.
--   * power system (integrated flare-poc, ci-zg3): the solar-flare cycle (drives
--     daytime + multiplier along the telegraph/ramp/plateau/decay curve and
--     applies battery heat upkeep) and the panel disposal-deficit damage sweep.
-- Everything here is scoped to surfaces named "cindra" (the individual modules
-- re-check), so no other planet is ever touched.
--
-- 🚨 on_nth_tick / on_init are REPLACE-not-add. Each periodic system uses a
-- DISTINCT N (snowfall 3, tile-damage 20, flare 23, panel-damage 29, freeze reheat 47);
-- native freeze onset itself is event-driven (on_chunk_generated), not a periodic tick.
-- The single on_init lives here (control.lua calls M.register once).

local tile_damage = require("scripts.tile-damage")
local feedback = require("scripts.damage-feedback")
local snowfall = require("scripts.snowfall")
local freeze_emitters = require("scripts.freeze-emitters")
local terrain = require("scripts.terrain")
local flare = require("scripts.flare")
local panels = require("scripts.panels")
local sinks = require("scripts.sinks")
local flare_config = require("scripts.flare-config")

local M = {}

-- Make the Cindra surface FINITE perpendicular to the ribbon (ci-3yl). The engine
-- IGNORES width/height set on a planet PROTOTYPE's map_gen_settings, so we set it
-- on the surface the moment it is created: the map-gen then fills everything
-- beyond +/- dim/2 with out-of-map (the void backstop), exactly the vanilla
-- ribbon-world mechanism. This is a ONE-TIME structural config of the map-gen, not
-- per-chunk void surgery -- no chunk is deleted, no tile is scripted.
-- Both axes are written, not just the finite one: the LONG axis is explicitly
-- reopened to 0 (infinite). A ribbon is bounded on ONE axis; a surface that
-- arrives carrying a bound on the long axis too (a world generated under the other
-- orientation, or any settings source with a size in it) would otherwise stay boxed
-- in on both axes -- the ci-65p horizontal-ribbon bug.
local function enforce_finite(surface)
  if not (surface and surface.valid) or surface.name ~= "cindra" then return end
  -- The total ribbon width is the SUM of the per-zone widths (ci-da2); terrain
  -- reads the per-zone width settings itself, so no cfg is needed here.
  local bounds = terrain.map_gen_bounds()
  local mg = surface.map_gen_settings
  local changed = false
  for key, value in pairs(bounds) do
    if mg[key] ~= value then
      mg[key] = value
      changed = true
    end
  end
  if changed then surface.map_gen_settings = mg end
end

-- Exposed so the orientation regression test can drive the real bounding code on a
-- live surface (tests/test_orientation.lua) instead of restating it.
M.enforce_finite = enforce_finite

-- Tests set storage.cindra_driver_enabled = false to keep the periodic sweeps
-- from firing during unrelated deterministic tests. Default (nil) = enabled.
local function driver_enabled()
  return storage.cindra_driver_enabled ~= false
end

local function for_each_cindra(fn)
  for _, s in pairs(game.surfaces) do
    if s.name == "cindra" then fn(s) end
  end
end

-- The lethal-ground damage sweep and the ambient THERMAL GRADE share one cadence,
-- purely because both want refreshing as the player moves -- they are otherwise
-- INDEPENDENT (ci-nw0). The sweep burns from the TILE under an entity (ci-ma18, so a
-- concrete cover shields); the grade is a cosmetic screen hue wash read from the
-- player's POSITION on the temperature axis, applying no damage and reading no damage
-- state. feedback.update_all walks connected players and is a no-op for anyone off
-- Cindra.
local function on_tile_damage_tick()
  if not driver_enabled() then return end
  for_each_cindra(function(s) tile_damage.sweep(s) end)
  feedback.update_all()
end

-- Advance the flare (daytime + multiplier along the curve) and bleed both
-- storage tiers' idle self-discharge: the molten-salt battery's punishing heat
-- upkeep and the capacitor's much gentler trickle (ci-411).
local function on_flare_tick(event)
  if not driver_enabled() then return end
  for_each_cindra(function(s)
    flare.apply(s, event.tick)
    sinks.apply_battery_upkeep(s)
    sinks.apply_capacitor_upkeep(s)
  end)
end

-- Morph freshly placed panels to their sunward-position output band (§ ci-9ht),
-- then run the panel disposal-deficit damage / recovery sweep on the settled
-- variants. Reconcile-then-sweep keeps the damage model reading each panel's real
-- position-scaled output.
local function on_panel_damage_tick()
  if not driver_enabled() then return end
  for_each_cindra(function(s)
    panels.reconcile_variants(s)
    panels.sweep(s)
  end)
end

-- Drift the icy-side snowfall (ci-mk5y): a purely cosmetic per-player flake field drawn
-- over the FROZEN half of the ribbon only. Its own fast cadence (snowfall.UPDATE_INTERVAL),
-- disjoint from every other periodic system, because the motion has to be smooth; a no-op
-- for any player off Cindra or off the ice.
local function on_snowfall_tick()
  if not driver_enabled() then return end
  snowfall.update_all()
end

-- NOT gated on driver_enabled: keeping the lava-heat emitters hot is infrastructure,
-- not a gameplay sweep. Tests that disable the driver to advance ticks deterministically
-- still need the warm band to stay thawed (the freeze flag is a prototype property that
-- is always live), so this maintenance runs regardless. It only re-sets emitter heat.
local function on_freeze_reheat_tick()
  for_each_cindra(function(s) freeze_emitters.reheat(s) end)
end

function M.register()
  script.on_nth_tick(tile_damage.DAMAGE_INTERVAL, on_tile_damage_tick)
  script.on_nth_tick(flare_config.FLARE_INTERVAL, on_flare_tick)
  script.on_nth_tick(flare_config.PANEL_DAMAGE_INTERVAL, on_panel_damage_tick)
  script.on_nth_tick(freeze_emitters.REHEAT_INTERVAL, on_freeze_reheat_tick)
  script.on_nth_tick(snowfall.UPDATE_INTERVAL, on_snowfall_tick)
  -- Bound the ribbon the instant its surface is created (the map-gen then voids
  -- beyond the band). The ribbon's tiles, resources and rocks are all generated by
  -- the map-gen itself (ci-3yl).
  script.on_event(defines.events.on_surface_created, function(event)
    enforce_finite(game.surfaces[event.surface_index])
  end)
  -- Native freeze (§ freeze, ci-bvk): line the invisible lava-heat emitters along
  -- the ribbon as chunks reveal, so the habitable band stays thawed on the
  -- entities_require_heating surface. Event-driven, gated to Cindra + the autoplace
  -- toggle inside the handler; disjoint from every periodic tick above.
  script.on_event(defines.events.on_chunk_generated, freeze_emitters.on_chunk_generated)
end

-- Called from control.lua's single on_init / on_configuration_changed.
function M.init()
  if storage.cindra_driver_enabled == nil then storage.cindra_driver_enabled = true end
  -- Bound any Cindra surface that already exists (mod added to a save, or a
  -- surface created before the handler registered). New chunks generate as void
  -- beyond the band; already-generated interior chunks are unaffected.
  for _, s in pairs(game.surfaces) do enforce_finite(s) end
  -- Seed the freeze autoplace toggle + line emitters across any already-generated
  -- Cindra chunks (mod added mid-save, or surface predating the chunk handler).
  freeze_emitters.init()
end

return M
