-- Cindra runtime driver (§15 items 2-3 worldgen + items 7-9 power).
--
-- Hooks every Cindra periodic system to the live game:
--   * worldgen track: the tile-based lethal-edge damage sweep (lava/deep-ice
--     tiles burn everything on them, player + machines) and the nightside
--     building-heat freeze. The RIBBON ITSELF (finite width, noise tile bands,
--     banded resources, finite rocks) is now generated by the MAP-GEN, so there
--     is NO on_chunk_generated terrain/void handler any more (ci-3yl).
--   * power system (integrated flare-poc, ci-zg3): the solar-flare cycle (drives
--     daytime + multiplier along the telegraph/ramp/plateau/decay curve and
--     applies battery heat upkeep) and the panel disposal-deficit damage sweep.
-- Everything here is scoped to surfaces named "cindra" (the individual modules
-- re-check), so no other planet is ever touched.
--
-- 🚨 on_nth_tick / on_init are REPLACE-not-add. Each periodic system uses a
-- DISTINCT N (tile-damage 20, building-heat 47, flare 23, panel-damage 29), and
-- the single on_init lives here (control.lua calls M.register once).

local tile_damage = require("scripts.tile-damage")
local building_heat = require("scripts.building-heat")
local terrain = require("scripts.terrain")
local flare = require("scripts.flare")
local panels = require("scripts.panels")
local sinks = require("scripts.sinks")
local flare_config = require("scripts.flare-config")

local M = {}

-- Make the Cindra surface FINITE perpendicular to the ribbon (ci-3yl). The engine
-- IGNORES width/height set on a planet PROTOTYPE's map_gen_settings, so we set it
-- on the surface the moment it is created: the map-gen then fills everything
-- beyond +/- dim/2 with out-of-map (the void backstop), exactly the vanilla
-- ribbon-world mechanism. This is a ONE-TIME structural config of the map-gen, not
-- per-chunk void surgery -- no chunk is deleted, no tile is scripted.
local function enforce_finite(surface)
  if not (surface and surface.valid) or surface.name ~= "cindra" then return end
  local s = settings and settings.startup
  local cfg = s and s["cindra-ribbon-wall-at"] and { wall_at = s["cindra-ribbon-wall-at"].value } or nil
  local d = terrain.finite_dimension(cfg)
  local mg = surface.map_gen_settings
  if mg[d.key] ~= d.value then
    mg[d.key] = d.value
    surface.map_gen_settings = mg
  end
end

-- Tests set storage.cindra_driver_enabled = false to keep the periodic sweeps
-- from firing during unrelated deterministic tests. Default (nil) = enabled.
local function driver_enabled()
  return storage.cindra_driver_enabled ~= false
end

local function for_each_cindra(fn)
  for _, s in pairs(game.surfaces) do
    if s.name == "cindra" then fn(s) end
  end
end

local function on_tile_damage_tick()
  if not driver_enabled() then return end
  for_each_cindra(function(s) tile_damage.sweep(s) end)
end

local function on_building_heat_tick()
  if not driver_enabled() then return end
  for_each_cindra(function(s) building_heat.sweep(s) end)
end

-- Advance the flare (daytime + multiplier along the curve) and bleed both
-- storage tiers' idle self-discharge: the molten-salt battery's punishing heat
-- upkeep and the capacitor's much gentler trickle (ci-411).
local function on_flare_tick(event)
  if not driver_enabled() then return end
  for_each_cindra(function(s)
    flare.apply(s, event.tick)
    sinks.apply_battery_upkeep(s)
    sinks.apply_capacitor_upkeep(s)
  end)
end

-- Morph freshly placed panels to their sunward-position output band (§ ci-9ht),
-- then run the panel disposal-deficit damage / recovery sweep on the settled
-- variants. Reconcile-then-sweep keeps the damage model reading each panel's real
-- position-scaled output.
local function on_panel_damage_tick()
  if not driver_enabled() then return end
  for_each_cindra(function(s)
    panels.reconcile_variants(s)
    panels.sweep(s)
  end)
end

function M.register()
  script.on_nth_tick(tile_damage.DAMAGE_INTERVAL, on_tile_damage_tick)
  script.on_nth_tick(building_heat.FREEZE_INTERVAL, on_building_heat_tick)
  script.on_nth_tick(flare_config.FLARE_INTERVAL, on_flare_tick)
  script.on_nth_tick(flare_config.PANEL_DAMAGE_INTERVAL, on_panel_damage_tick)
  -- Bound the ribbon the instant its surface is created (the map-gen then voids
  -- beyond the band). No on_chunk_generated: the ribbon's tiles, resources and
  -- rocks are all generated by the map-gen itself (ci-3yl).
  script.on_event(defines.events.on_surface_created, function(event)
    enforce_finite(game.surfaces[event.surface_index])
  end)
end

-- Called from control.lua's single on_init / on_configuration_changed.
function M.init()
  if storage.cindra_driver_enabled == nil then storage.cindra_driver_enabled = true end
  building_heat.init()
  -- Bound any Cindra surface that already exists (mod added to a save, or a
  -- surface created before the handler registered). New chunks generate as void
  -- beyond the band; already-generated interior chunks are unaffected.
  for _, s in pairs(game.surfaces) do enforce_finite(s) end
end

return M
