-- Ribbon TERRAIN as REAL noise-driven map-gen (§4, §15-2; ci-3yl, per-zone widths ci-a35).
--
-- The ribbon is generated by the MAP-GEN itself, not by an on_chunk_generated
-- script. This module is the single source of truth for the tile BANDS: it maps
-- the perpendicular (sunward-nightward) axis to an ORDERED set of Cindra-exclusive
-- tiles, each placed by a Factorio NOISE EXPRESSION keyed to that axis. The engine
-- picks, per tile, the candidate with the highest `probability_expression`, so the
-- bands arrange themselves; a smooth `basis_noise` term is added to the axis
-- coordinate so every band boundary is an ORGANIC wavy curve, never a straight line.
--
-- The full hot->cold gradient (ci-a35), from the SUNWARD (hot) edge inward to the
-- NIGHTWARD (cold) edge -- the planet's whole thesis painted onto the ground:
--
--   hot-lava -> lava -> volcanic-cracks (hot/warm/plain) -> jagged -> dry-dirt ->
--   dirt -> [ SAND: the temperate spawn centre ] -> aquilo-dust -> rough-ice -> smooth-ice
--
-- Only the molten EDGE (hot-lava + lava, heat) and the deep ICE edge (smooth-ice,
-- cold) are lethal (scripts/tile-damage.lua reads M.lethal_kind); everything from
-- the volcanic cracks inward through the sand centre out to rough-ice is WALKABLE,
-- buildable, SAFE margin. The wide SAND band at the centre is the safe landing spawn.
--
-- PER-ZONE WIDTHS (ci-a35): each zone's width is an independent mod setting
-- (settings.lua, `cindra-zone-width-<key>`). The generated world's perpendicular
-- extent is the SUM of every zone width, so widening any one band widens both that
-- band AND the whole ribbon. The hot-lava band is band #1 and ALWAYS generates at
-- the sunward extreme (its width setting has a floor of 1 and its noise expression
-- extends out to the void edge), so a hot-lava layer is guaranteed at any settings.
--
-- The world is finite PERPENDICULAR to the ribbon via the map-gen's own `width`
-- (vertical orientation) / `height` (horizontal): the engine fills everything
-- beyond +/- SUM/2 with `out-of-map`, so the void backstop emerges from the
-- map-gen, not a script. See M.finite_dimension / prototypes/planet.lua.
--
-- PURE where it counts: the layout maths, the *_expr emitters and lethal_kind are
-- plain string/table logic (no game.* / prototypes.*), so the bands are
-- unit-testable off the game (unit-tests/test_terrain.lua). Widths fall back to
-- their defaults when `settings` is absent (plain-Lua tests). The clone-source
-- table is consumed only at the data stage (prototypes/tiles.lua). Bands read the
-- SAME perpendicular axis as scripts/ribbon.lua (via scripts/axis.lua), so the
-- VISIBLE terrain and the FELT damage share one axis.

local axis = require("scripts.axis")

local M = {}

-- The Cindra tile gradient, ordered from the HOT (sunward) edge inward to the COLD
-- (nightward) edge. Each entry is a NEW `cindra-*` prototype cloned
-- (prototypes/tiles.lua) from a vanilla tile purely for its art; we never enable
-- or mutate the vanilla tile itself, so nothing leaks onto Nauvis / Vulcanus / Aquilo.
--   name        the cindra-* tile prototype
--   clone_from  vanilla tile whose art it borrows
--   key         the width-setting suffix (`cindra-zone-width-<key>`) + cfg override key
--   default     default band width (tiles); (tune)
--   lethal      "heat" / "cold" / nil -- the damage kind scripts/tile-damage.lua inflicts
--   peak        probability plateau height (higher wins overlaps -> outer bands win the edge)
--   center      true for the single spawn band (the constant baseline, perp 0)
--
-- Default widths are balanced so the HOT half (96) equals the COLD half (96) with a
-- wide SAND centre (48): the geometric centre of the ribbon (world 0,0, the landing
-- spawn) lands squarely in the sand band. Total default extent = 240 tiles.
M.ZONES = {
  { name = "cindra-hot-lava",             clone_from = "lava-hot",               key = "hot-lava",             default = 8,  lethal = "heat", peak = 4 },
  { name = "cindra-lava",                 clone_from = "lava",                   key = "lava",                 default = 10, lethal = "heat", peak = 3 },
  { name = "cindra-volcanic-cracks-hot",  clone_from = "volcanic-cracks-hot",    key = "volcanic-cracks-hot",  default = 12, lethal = nil,    peak = 2 },
  { name = "cindra-volcanic-cracks-warm", clone_from = "volcanic-cracks-warm",   key = "volcanic-cracks-warm", default = 12, lethal = nil,    peak = 2 },
  { name = "cindra-volcanic-cracks",      clone_from = "volcanic-cracks",        key = "volcanic-cracks-plain",default = 12, lethal = nil,    peak = 2 },
  { name = "cindra-jagged",               clone_from = "volcanic-jagged-ground", key = "jagged",               default = 14, lethal = nil,    peak = 2 },
  { name = "cindra-dry-dirt",             clone_from = "dry-dirt",               key = "dry-dirt",             default = 14, lethal = nil,    peak = 2 },
  { name = "cindra-dirt",                 clone_from = "dirt-3",                 key = "dirt",                 default = 14, lethal = nil,    peak = 2 },
  { name = "cindra-sand",                 clone_from = "sand-1",                 key = "sand",                 default = 48, lethal = nil,    peak = 1, center = true },
  { name = "cindra-aquilo-dust",          clone_from = "dust-flat",              key = "aquilo-dust",          default = 32, lethal = nil,    peak = 2 },
  { name = "cindra-rough-ice",            clone_from = "ice-rough",              key = "rough-ice",            default = 32, lethal = nil,    peak = 2 },
  { name = "cindra-smooth-ice",           clone_from = "ice-smooth",             key = "smooth-ice",           default = 32, lethal = "cold", peak = 4 },
}

-- The centre (spawn) tile: the constant baseline candidate that wins the wide safe
-- middle and is the universal fallback (the engine has no default tile).
M.CENTER = "cindra-sand"

-- Prefix + floor for the per-zone width settings. The hot-lava band must always
-- generate (bead ci-a35), so its width setting floors at 1; every other zone may
-- go to 0 to remove that band. The data stage (settings.lua) mirrors these.
M.WIDTH_SETTING_PREFIX = "cindra-zone-width-"
M.HOT_LAVA_MIN_WIDTH = 1

-- Smooth-noise amplitude (tiles) and wavelength (tiles) that wiggles the band
-- boundaries so they are organic, never straight. Fixed seed -> the ribbon has the
-- same band structure on every map seed (a ribbon world is a fixed shape, not a
-- per-seed lottery), and it stays deterministic for tests. Kept BELOW half the
-- thinnest band's exclusive core so a band never wiggles out of existence. (tune)
M.NOISE_AMPLITUDE = 3
M.NOISE_WAVELENGTH = 48

-- Band-boundary overlap (tiles): neighbouring bands overlap by this much so no
-- sliver of the centre tile ever bleeds between two coloured bands, and the slope
-- over which a plateau ramps to 0 at its edges. Kept SMALL so even the thin hot
-- bands (hot-lava 8, lava 10) keep an exclusive core that no neighbour claims. The
-- outermost hot/cold bands extend `EDGE_EXTEND` past the void edge so they always
-- reach the map boundary. (tune)
M.OVERLAP = 2
M.SLOPE = 3
M.EDGE_EXTEND = 64

-- Format a number for the noise DSL (integers stay clean, no float noise).
local function num(v)
  if v == math.floor(v) then return string.format("%d", v) end
  return string.format("%.6g", v)
end

-- Read a single zone width: an explicit cfg override (keyed by zone.key) wins,
-- then the mod setting, then the zone default. Pure-safe: falls back to the
-- default when `settings` is absent (plain-Lua unit tests).
local function zone_width(zone, cfg)
  local w
  if cfg and cfg[zone.key] ~= nil then
    w = cfg[zone.key]
  else
    local s = settings and settings.startup and settings.startup[M.WIDTH_SETTING_PREFIX .. zone.key]
    w = s and s.value or zone.default
  end
  if zone.key == "hot-lava" and w < M.HOT_LAVA_MIN_WIDTH then w = M.HOT_LAVA_MIN_WIDTH end
  if w < 0 then w = 0 end
  return w
end

-- The signed perpendicular layout (ci-a35): the width of every zone and its band
-- interval on the sunward-positive perpendicular axis. Zones stack from the hot
-- edge (largest +perp) inward to the cold edge (largest -perp); the ribbon is
-- centred so perp 0 (world 0,0, the spawn) sits at the geometric middle. Returns:
--   total          sum of all zone widths = the finite perpendicular extent
--   half           total / 2 (the +/- perp map edge)
--   bands[name]    { lo, hi, zone } band interval (lo < hi), hot-positive perp
-- Pure: no game.* access.
function M.layout(cfg)
  local widths, total = {}, 0
  for _, z in ipairs(M.ZONES) do
    local w = zone_width(z, cfg)
    widths[z.name] = w
    total = total + w
  end
  local half = total / 2
  local bands = {}
  local c = 0 -- cumulative distance from the hot edge
  for _, z in ipairs(M.ZONES) do
    local w = widths[z.name]
    -- perp is hot-positive: the hot edge of the band (nearer the sun) is the
    -- LARGER perp; stepping inward (cold-ward) lowers perp.
    local hi = half - c
    local lo = half - (c + w)
    bands[z.name] = { lo = lo, hi = hi, zone = z, width = w }
    c = c + w
  end
  return { total = total, half = half, bands = bands }
end

-- The sunward-positive perpendicular coordinate as a noise-expression string,
-- wiggled by a smooth basis-noise term so band boundaries are organic curves.
-- scripts/axis.lua owns which world axis is perpendicular; we never re-derive it.
local function perp_wiggled()
  local n = "basis_noise{x = x, y = y, seed0 = 1, seed1 = 7" ..
            ", input_scale = " .. num(1 / M.NOISE_WAVELENGTH) ..
            ", output_scale = " .. num(M.NOISE_AMPLITUDE) .. "}"
  return "(" .. axis.perp_expr() .. " + " .. n .. ")"
end

-- range_select_base(input, from, to, slope, min, max): `min` outside [from,to]
-- (ramping over `slope`), `max` inside. Our band plateau selector.
local function rsb(input, from, to, slope, lo, hi)
  return "range_select_base(" .. input .. ", " .. num(from) .. ", " .. num(to) ..
         ", " .. num(slope) .. ", " .. num(lo) .. ", " .. num(hi) .. ")"
end

-- The `probability_expression` string for a Cindra tile, given the width cfg.
-- The SAND centre is a constant baseline of 1 (the wide safe spawn + the universal
-- fallback guaranteeing full coverage). Every other band peaks above 1 inside its
-- perp interval; higher peaks (lethal edges) win overlaps, so the outer bands claim
-- the edge. The two extreme bands (hot-lava, smooth-ice) extend their plateau past
-- the void edge, so a hot-lava band ALWAYS reaches the sunward map boundary and a
-- smooth-ice band the nightward boundary, at any width settings (ci-a35).
function M.probability_expr(name, cfg)
  local L = M.layout(cfg)
  local band = L.bands[name]
  if not band then error("terrain: unknown Cindra tile " .. tostring(name)) end
  local z = band.zone
  if z.center then
    return "1" -- constant baseline: the wide safe spawn centre + the fallback.
  end
  local perp = perp_wiggled()
  local from = band.lo - M.OVERLAP
  local to = band.hi + M.OVERLAP
  -- The outermost hot/cold bands reach the void edge so their layer is guaranteed.
  if name == M.ZONES[1].name then to = L.half + M.EDGE_EXTEND end
  if name == M.ZONES[#M.ZONES].name then from = -L.half - M.EDGE_EXTEND end
  return rsb(perp, from, to, M.SLOPE, 0, z.peak)
end

-- "heat" / "cold" / nil: the damage kind a lethal tile inflicts (nil = safe).
-- scripts/tile-damage.lua reads this to damage everything standing on a lethal
-- tile; every walkable margin returns nil.
function M.lethal_kind(name)
  for _, z in ipairs(M.ZONES) do
    if z.name == name then return z.lethal end
  end
  return nil
end

-- The set of every lethal tile name -> its damage kind (built once).
function M.lethal_tiles()
  local out = {}
  for _, z in ipairs(M.ZONES) do
    if z.lethal then out[z.name] = z.lethal end
  end
  return out
end

-- All Cindra tile names (for the map-gen autoplace_settings.tile allow-list).
function M.tile_names()
  local out = {}
  for _, z in ipairs(M.ZONES) do out[#out + 1] = z.name end
  return out
end

-- The FINITE map dimension (tiles) that bounds the ribbon perpendicular to its
-- long axis, and which basic setting it maps to. The extent is the SUM of every
-- zone width (ci-a35): the engine voids everything beyond +/- extent/2, so the
-- ribbon is finite perpendicular straight from the map-gen. Vertical ribbon ->
-- bound X (`width`); horizontal -> bound Y (`height`).
function M.finite_dimension(cfg)
  return {
    key = (axis.orientation() == axis.HORIZONTAL) and "height" or "width",
    value = M.layout(cfg).total,
  }
end

return M
