-- Ribbon TERRAIN as REAL noise-driven map-gen (§4, §15-2; ci-3yl, reworked ci-da2).
--
-- The ribbon is generated by the MAP-GEN itself, not by an on_chunk_generated
-- script. This module is the single source of truth for the tile ZONES: a full
-- LEFT->RIGHT gradient across the perpendicular (sunward-nightward) axis, from a
-- lethal molten HOT edge on the west, through the temperate building ribbon, out
-- to a lethal frozen edge on the east. Each zone is a band of a given WIDTH along
-- the axis, placed by a Factorio NOISE EXPRESSION keyed to that axis; a smooth
-- basis_noise term is added to the coordinate so every band boundary is an ORGANIC
-- wavy curve and adjacent zones interpenetrate as a noisy gradient, never a raw
-- straight stripe.
--
-- DEFINITIVE zone layout (ci-da2), HOT (west, -X) -> COLD (east, +X):
--
--   1 hot-lava    2 lava    3 lava-crust    4 volcanic-warm    5 basalt
--   6 scorched    7 dry-sand    8 BUILDING (wide safe spawn)    9 cold-dust
--   10 rough-ice    11 deep-ice (the ice cap beyond the cliff)
--
--   * WIDTH per zone (tiles), (tune) defaults 50 each except the 200-wide building
--     area and the 250-wide ice cap. Each width is a mod setting; the TOTAL ribbon
--     width is DERIVED = the SUM of all zone widths (ci-a35 / ci-da2 clarification):
--     changing one zone's width changes only that band and the total, never rescales
--     the others. The whole gradient is centred on the map origin so the building
--     band sits at spawn on the default (balanced) widths.
--   * NOT WALKABLE: hot-lava + lava (impassable like Vulcanus lava; the hot
--     backstop). Every other zone is walkable, buildable ground.
--   * LETHAL (damaging) tiles: hot-lava, lava, lava-crust (heat) and deep-ice
--     (cold). scripts/tile-damage.lua reads M.lethal_kind; the walkable middle is
--     safe. The impassable hot pair can't be stood on, so their lethality is the
--     wall itself; lava-crust + deep-ice are the walkable-but-damaging edges that
--     reward edge-pushing.
--
-- The world is finite PERPENDICULAR to the ribbon via the map-gen's own `width`
-- (vertical orientation) / `height` (horizontal): the engine fills everything
-- beyond +/- TOTAL/2 with `out-of-map`, so the void backstop emerges from the
-- map-gen. See M.finite_dimension / prototypes/planet.lua.
--
-- PURE where it counts: the *_expr emitters, the zone table, the band geometry and
-- lethal_kind are plain string/table logic (no game.* / prototypes.*), so the zones
-- are unit-testable off the game (unit-tests/test_terrain.lua). The clone-source
-- table is consumed only at the data stage (prototypes/tiles.lua). Boundaries read
-- the SAME perpendicular axis as scripts/ribbon.lua, so the VISIBLE terrain and the
-- FELT damage share one axis; scripts/resource-field.lua reads M.resource_bounds so
-- resources band to the SAME zones (stone on the hot ribbon, ice on the cold cap).

local axis = require("scripts.axis")

local M = {}

-- The Cindra tile ZONES, ordered HOT (west) -> COLD (east). Each is a NEW `cindra-*`
-- prototype cloned (prototypes/tiles.lua) from a vanilla tile for its art; we never
-- enable or mutate the vanilla tile itself, so nothing leaks onto Nauvis. Fields:
--   name        the cindra-* tile prototype name
--   clone_from  the vanilla tile whose art it borrows (see the family in the spec)
--   width       default band width in tiles (the mod-setting default); the total
--               ribbon width is the SUM of these
--   setting     the per-zone width mod-setting name (settings.lua)
--   walkable    false => impassable lava (keeps the fluid/lava collision); the two
--               hot lava zones. true => buildable/walkable ground.
--   lethal      "heat" | "cold" | nil: the damage kind tile-damage.lua inflicts.
--   role        stable key used by geometry helpers + resource banding.
--   map_color   {r,g,b} 0..1: the coordinated hot->cold map-view gradient (ci-4h7)
--               so the danger zone reads at a glance (reds sunward, cyan nightward,
--               a neutral sandy building centre between the two coloured edges).
M.ZONES = {
  { role = "hot_lava",      name = "cindra-hot-lava",      clone_from = "lava-hot",              width = 50,  setting = "cindra-zone-width-hot-lava",      walkable = false, lethal = "heat", map_color = { 0.98, 0.45, 0.05 } },
  { role = "lava",          name = "cindra-lava",          clone_from = "lava",                  width = 50,  setting = "cindra-zone-width-lava",          walkable = false, lethal = "heat", map_color = { 0.92, 0.30, 0.05 } },
  { role = "lava_crust",    name = "cindra-lava-crust",    clone_from = "volcanic-cracks-hot",   width = 50,  setting = "cindra-zone-width-lava-crust",    walkable = true,  lethal = "heat", map_color = { 0.78, 0.22, 0.08 } },
  { role = "volcanic_warm", name = "cindra-volcanic-warm", clone_from = "volcanic-cracks-warm",  width = 50,  setting = "cindra-zone-width-volcanic-warm", walkable = true,  lethal = nil,    map_color = { 0.60, 0.26, 0.14 } },
  { role = "basalt",        name = "cindra-basalt",        clone_from = "volcanic-jagged-ground", width = 50, setting = "cindra-zone-width-basalt",        walkable = true,  lethal = nil,    map_color = { 0.42, 0.32, 0.26 } },
  { role = "scorched",      name = "cindra-scorched-dirt", clone_from = "volcanic-soil-light",   width = 50,  setting = "cindra-zone-width-scorched",      walkable = true,  lethal = nil,    map_color = { 0.52, 0.42, 0.28 } },
  { role = "dry_sand",      name = "cindra-dry-sand",      clone_from = "red-desert-1",          width = 50,  setting = "cindra-zone-width-dry-sand",      walkable = true,  lethal = nil,    map_color = { 0.66, 0.52, 0.32 } },
  { role = "terminator",    name = "cindra-terminator",    clone_from = "sand-2",                width = 200, setting = "cindra-zone-width-building",      walkable = true,  lethal = nil,    map_color = { 0.55, 0.50, 0.40 } },
  { role = "cold_dust",     name = "cindra-cold-dust",     clone_from = "dust-flat",             width = 50,  setting = "cindra-zone-width-cold-dust",     walkable = true,  lethal = nil,    map_color = { 0.60, 0.64, 0.66 } },
  { role = "rough_ice",     name = "cindra-rough-ice",     clone_from = "ice-rough",             width = 50,  setting = "cindra-zone-width-rough-ice",     walkable = true,  lethal = nil,    map_color = { 0.62, 0.80, 0.88 } },
  { role = "deep_ice",      name = "cindra-deep-ice",      clone_from = "ice-smooth",            width = 250, setting = "cindra-zone-width-deep-ice",      walkable = true,  lethal = "cold", map_color = { 0.78, 0.95, 1.00 } },
}

-- Back-compat alias: prototypes/tiles.lua and tile_names iterate the zone list.
M.TILES = M.ZONES

-- Convenience lookups.
M.CENTER = "cindra-terminator"
M.NAME = {}
for _, z in ipairs(M.ZONES) do M.NAME[z.role] = z.name end

-- The index of the wide safe building band (spawn) in M.ZONES.
M.BUILDING_ROLE = "terminator"
local BUILDING_INDEX
for i, z in ipairs(M.ZONES) do
  if z.role == M.BUILDING_ROLE then BUILDING_INDEX = i end
end

-- Smooth-noise amplitude (tiles) and wavelength (tiles) that wiggles every band
-- boundary so the bands are organic, never straight, and adjacent zones blend.
-- Fixed seeds -> the ribbon has the same zone structure on every map seed (a
-- ribbon planet is a fixed shape, not a per-seed lottery) and stays deterministic
-- for tests. (tune)
M.NOISE_AMPLITUDE = 7
M.NOISE_WAVELENGTH = 48

-- Format a number for the noise DSL (integers stay clean, no float noise).
local function num(v)
  if v == math.floor(v) then return string.format("%d", v) end
  return string.format("%.6g", v)
end

-- ---------------------------------------------------------------------------
-- Zone widths + band geometry (PURE: no game.* access).
--
-- Widths come from the per-zone mod settings when a startup `settings` table is
-- present (data/control stage); a `cfg` table keyed by role overrides them (tests);
-- otherwise the zone-table defaults apply (plain-Lua unit tests, no settings).
-- ---------------------------------------------------------------------------
function M.widths(cfg)
  cfg = cfg or {}
  local s = settings and settings.startup
  local out = {}
  for i, z in ipairs(M.ZONES) do
    local w = cfg[z.role]
    if w == nil and s and s[z.setting] then w = s[z.setting].value end
    if w == nil then w = z.width end
    out[i] = w
  end
  return out
end

-- The signed perpendicular band [lo, hi] (sunward-positive coordinate p = the
-- axis, hot = high p) each zone occupies, plus the total ribbon width. The whole
-- gradient is centred on the origin: the hot edge sits at +TOTAL/2, the cold edge
-- at -TOTAL/2, and zones stack inward from the hot edge in order. Returns
-- (bands, total) where bands is parallel to M.ZONES.
function M.bands(cfg)
  local w = M.widths(cfg)
  local total = 0
  for _, v in ipairs(w) do total = total + v end
  local bands = {}
  local p = total / 2 -- the hot (sunward) edge, highest perpendicular coordinate
  for i = 1, #w do
    bands[i] = { lo = p - w[i], hi = p }
    p = p - w[i]
  end
  return bands, total
end

-- The perp-axis boundaries scripts/resource-field.lua bands resources against, so
-- resources track the SAME zones as the tiles:
--   building_half : |p| <= this is the safe building/terminator ribbon
--   building_lo   : the cold (east) edge of the building band; the stone/ice divider
--   hot_edge      : the outer edge of the last WALKABLE hot zone (lava-crust); stone
--                   reaches to here (the richest, most dangerous stone), never into
--                   the impassable lava beyond
--   cold_edge     : the far cold (east) edge of the ribbon (the ice cap edge)
-- Splitting stone (p >= building_lo) from ice (p < building_lo) at the one divider
-- keeps the zone-purity guarantee (stone never in the icy zone, ice never in the
-- hot/temperate zone) as pure geometry.
function M.resource_bounds(cfg)
  local bands = M.bands(cfg)
  local b = bands[BUILDING_INDEX]
  local hot_edge = b.hi
  for i = BUILDING_INDEX - 1, 1, -1 do
    if M.ZONES[i].walkable then hot_edge = bands[i].hi else break end
  end
  return {
    building_half = b.hi,
    building_lo = b.lo,
    hot_edge = hot_edge,
    cold_edge = bands[#bands].lo,
  }
end

-- ---------------------------------------------------------------------------
-- Noise-expression emitters.
-- ---------------------------------------------------------------------------

-- The sunward-positive perpendicular axis as a noise-expression string. axis.lua
-- owns which world axis is perpendicular; we never re-derive it.
local function perp_expr() return axis.perp_expr() end

-- A smooth basis-noise term ~+/-NOISE_AMPLITUDE tiles at ~NOISE_WAVELENGTH pitch.
-- `seed1` varies the field so each zone's boundaries wiggle independently.
local function noise(seed1)
  return "basis_noise{x = x, y = y, seed0 = 1, seed1 = " .. num(seed1) ..
         ", input_scale = " .. num(1 / M.NOISE_WAVELENGTH) ..
         ", output_scale = " .. num(M.NOISE_AMPLITUDE) .. "}"
end

-- max(0, expr): the linear falloff outside a band.
local function relu(expr)
  return "max(0, " .. expr .. ")"
end

-- The `probability_expression` string for a Cindra zone tile, given the widths.
-- Each zone is a PLATEAU (flat, high) inside its perpendicular band [lo, hi] that
-- falls off linearly outside it; the engine places, per tile, the candidate with
-- the highest probability, so at every point the nearest band wins -> the whole
-- finite width is covered with no gaps, and boundaries fall exactly at the shared
-- zone edges. The axis coordinate is perturbed by basis_noise, so the boundaries
-- wiggle organically and adjacent zones interpenetrate (never a raw straight line).
-- PLATEAU keeps the winning value comfortably positive everywhere in the ribbon.
M.PLATEAU = 1000
function M.probability_expr(name, cfg)
  local bands = M.bands(cfg)
  for i, z in ipairs(M.ZONES) do
    if z.name == name then
      local b = bands[i]
      local P = "(" .. perp_expr() .. " + " .. noise(10 + i) .. ")"
      return num(M.PLATEAU) .. " - (" .. relu(num(b.lo) .. " - " .. P) ..
             " + " .. relu(P .. " - " .. num(b.hi)) .. ")"
    end
  end
  error("terrain: unknown Cindra tile " .. tostring(name))
end

-- The map-view colour (a {r,g,b} 0..1 table) for a Cindra tile, or nil if unknown.
function M.map_color(name)
  for _, z in ipairs(M.ZONES) do
    if z.name == name then return z.map_color end
  end
  return nil
end

-- "heat" / "cold" / nil: the damage kind a lethal tile inflicts (nil = safe).
function M.lethal_kind(name)
  for _, z in ipairs(M.ZONES) do
    if z.name == name then return z.lethal end
  end
  return nil
end

-- The set of every lethal tile name -> its damage kind (built once per call).
function M.lethal_tiles()
  local out = {}
  for _, z in ipairs(M.ZONES) do
    if z.lethal then out[z.name] = z.lethal end
  end
  return out
end

-- True if a tile is walkable/buildable ground (false = impassable lava), or nil
-- for an unknown tile. prototypes/tiles.lua reads this to keep the two hot lava
-- zones impassable while every other zone is buildable ground.
function M.is_walkable(name)
  for _, z in ipairs(M.ZONES) do
    if z.name == name then return z.walkable end
  end
  return nil
end

-- All Cindra tile names (for the map-gen autoplace_settings.tile allow-list).
function M.tile_names()
  local out = {}
  for _, z in ipairs(M.ZONES) do out[#out + 1] = z.name end
  return out
end

-- The FINITE map dimension (tiles) that bounds the ribbon perpendicular to its
-- long axis, and which basic setting it maps to. The value is the TOTAL ribbon
-- width = the SUM of all zone widths (ci-da2 clarification): the engine voids
-- everything beyond +/- value/2, and because the gradient is centred on the
-- origin that crop lines up with the hot and cold edges. Vertical ribbon -> bound
-- X (`width`); horizontal -> bound Y (`height`).
function M.finite_dimension(cfg)
  local _, total = M.bands(cfg)
  return {
    key = (axis.orientation() == axis.HORIZONTAL) and "height" or "width",
    value = total,
  }
end

return M
