-- Ribbon TERRAIN as REAL noise-driven map-gen (§4, §15-2; ci-3yl, reworked ci-da2,
-- rebuilt ci-wly as a THREE-PART, TWO-HEIGHTMAP planet).
--
-- The ribbon is generated by the MAP-GEN itself, not by an on_chunk_generated script.
-- This module is the single source of truth for the tile layout. Per the ci-wly
-- playtest redesign the planet is THREE regions across the perpendicular (sunward->
-- nightward) axis, HOT (west, +perp) -> HABITABLE MIDDLE -> COLD (east, -perp), the hot
-- and cold sides ~equal in width. Each side is an OCEAN + a damaging INNER slope
-- painted by a HEIGHTMAP, plus a safe cool OUTER slope painted by a flat noisy MIX:
--
--   === HOT SIDE (ocean of hot-lava -> ash-dark) ===
--   ocean of hot-lava -> lava -> volcanic-smooth-stone-warm -> volcanic-cracks-hot     (heightmap)
--   -> volcanic-cracks-warm -> volcanic-cracks -> volcanic-smooth-stone -> ash-dark     (flat outer slope)
--   (The ci-72bw folds/pumice BRANCH after cracks-hot is a staged follow-up.)
--
--   === COLD SIDE (ocean of smooth-ice -> ash-light) ===
--   ocean of smooth-ice -> rough-ice -> snow-patchy -> snow-lumpy -> snow-crests ->
--   snow-flat                                                                          (heightmap)
--   -> dust-patchy -> dust-lumpy -> dust-crests -> dust-flat -> volcanic-ash-light      (flat outer slope)
--
--   === MIDDLE (habitable) ===
--   a noisy mix of volcanic-ash-dark / volcanic-ash-light / volcanic-ash-flats, with
--   SMALL soil patches (ash-soil -> soil-light -> soil-dark, nested by a patch field).
--
-- THE TWO OCEANS ARE FOLDED INTO THE HEIGHTMAP (ci-7jc): each ocean is the ELEVATION
-- PEAK of its side (a forced elevation floor confined to the ocean band), so lava / ice
-- radiate OUTWARD from the ocean as concentric contour rings and thin to nothing by the
-- inner-slope edge -- the ocean is never "stamped on top" of a finished map. Each ocean
-- is ~200 tiles of nothing but ocean ("it goes on forever") before the finite map edge.
--
-- WHY THE OUTER SLOPES ARE FLAT (not heightmap): the damaging tiles (lava, warm smooth
-- stone, cracks-hot; smooth/rough ice, patchy snow) live in the heightmap, confined to
-- the ocean+inner region by a STEEP perpendicular gate. That keeps a SAFE cool band
-- (the outer slope + middle) where the harvestable stone/ice fields live, exactly like
-- the proven ci-da2/ci-cwk model (heightmap for the hot core, flat cool zones for the
-- resource band). The outer slopes are a noisy MIX of the cool tiles (a plateau + an
-- interpolated membership weight + a per-tile speckle) so members interpenetrate as an
-- organic gradient, blending into the ash middle.
--
-- WIDTHS. Each zone width is a mod setting (settings.lua); the TOTAL is the SUM.
-- Defaults sum to 800 with the hot side (200+70+70) equal to the cold side, so the
-- 120-wide MIDDLE straddles the origin (spawn). Changing one width changes only that
-- band + the total.
--
-- WALKABILITY is per-TILE. Only the two lava tiles are impassable (molten fluid), so
-- the hot-lava ocean is the one hard WALL. The smooth-ice ocean is now WALKABLE (you can
-- RUN on it, it just freezes you) -- ci-wly drops the old impassable ice-wall. Every
-- other tile is buildable ground.
--
-- DAMAGE is PER TILE (ci-4jl), scaling with depth. HEAT: hot-lava(1) > lava >
-- smooth-stone-warm > cracks-hot > cracks-warm. COLD: smooth-ice(1) > rough-ice >
-- snow-patchy. The POSITIONAL descriptors (M.damage_bounds / M.lethal_at) mark which
-- BAND is heat/cold for the resource keep-back geometry.
--
-- NO-PAVE HAZARD TILES (ci-wly, extends ci-cbn, closes ci-8vu): you cannot pave atop
-- M.NO_PAVE (hot-lava, lava, smooth-stone-warm, cracks-hot, smooth-ice, rough-ice);
-- scripts/no-paving.lua reverts any tile built on one on the cindra surface.
--
-- The world is finite PERPENDICULAR via the map-gen's own `width`/`height`.
--
-- PURE where it counts: the zone table, band geometry, ring/flat membership, the
-- probability/mask emitters, the damage table and the bounds are plain string/table
-- logic (no game.* / prototypes.*), unit-testable off the game (test_terrain.lua).

local axis = require("scripts.axis")

local M = {}

-- ---------------------------------------------------------------------------
-- The ordered Cindra tile ZONES, HOT (west, +perp) -> COLD (east, -perp). Fields:
--   role     stable key for geometry helpers, settings + resource banding.
--   width    default band width in tiles (the mod-setting default).
--   setting  the per-zone width mod-setting name (settings.lua).
--   region   "hot"    -> painted by the hot heightmap (ocean + inner);
--            "hot_flat" | "middle" | "cold_flat" -> painted by a flat noisy mix;
--            "cold"   -> painted by the cold heightmap (inner + ocean).
--   ocean    true => the region's OCEAN (the elevation peak; a forced solid sea).
--   wall     true => a pure impassable lava wall (the hot ocean).
--   damage   "heat" | "cold" | nil: the environmental damage this BAND marks
--            (positional descriptor for resource keep-back; see M.damage_bounds).
-- ---------------------------------------------------------------------------
M.ZONES = {
  { role = "hot_ocean",  width = 200, setting = "cindra-zone-width-hot-ocean",
    region = "hot", ocean = true, wall = true, damage = "heat" },
  { role = "hot_inner",  width = 70,  setting = "cindra-zone-width-hot-inner",
    region = "hot", damage = "heat" },
  { role = "hot_outer",  width = 70,  setting = "cindra-zone-width-hot-outer",
    region = "hot_flat" },
  { role = "middle",     width = 120, setting = "cindra-zone-width-middle",
    region = "middle" },
  { role = "cold_outer", width = 70,  setting = "cindra-zone-width-cold-outer",
    region = "cold_flat" },
  { role = "cold_inner", width = 70,  setting = "cindra-zone-width-cold-inner",
    region = "cold", damage = "cold" },
  { role = "cold_ocean", width = 200, setting = "cindra-zone-width-cold-ocean",
    region = "cold", ocean = true, damage = "cold" },
}

-- The index of the wide safe MIDDLE band (spawn).
M.BUILDING_ROLE = "middle"
local BUILDING_INDEX
for i, z in ipairs(M.ZONES) do
  if z.role == M.BUILDING_ROLE then BUILDING_INDEX = i end
end

-- The cindra-* tile name for a vanilla clone source (deterministic prefix).
local function cindra_name(vanilla) return "cindra-" .. vanilla end
M.cindra_name = cindra_name

-- ---------------------------------------------------------------------------
-- HEIGHTMAP RING orders (core -> outer), one per side. `lo` is the ring's LOWER
-- elevation threshold; its upper threshold is the previous ring's `lo`. The tile whose
-- band contains the elevation E wins, so equal-E contours nest as concentric rings. The
-- ocean tile is the CORE (the forced ocean floor pins E above the core threshold across
-- the ocean band). Confined to the side's OCEAN+INNER region by a steep perpendicular
-- gate, so the damaging tiles never reach the safe outer slope / resource band.
-- ---------------------------------------------------------------------------
local RING_BIG = 1e9

-- HOT heightmap (the damaging rings): lava core -> cracks-hot, then cracks-warm as the
-- outermost open-bottom ring blending into the flat hot outer slope. Keeps the proven
-- ci-cwk thresholds so the lava sea + pools are untouched.
M.HOT_RING_ORDER = {
  { vanilla = "lava-hot",                   lo = 140 },       -- molten CORE / ocean peak
  { vanilla = "lava",                       lo = 90 },        -- pool body
  { vanilla = "volcanic-smooth-stone-warm", lo = 45 },        -- warm crust ring, adjacent to lava
  { vanilla = "volcanic-cracks-hot",        lo = 15 },        -- cracks-hot ring, outside smooth-stone
  { vanilla = "volcanic-cracks-warm",       lo = -RING_BIG }, -- outermost, blends to the flat slope
}

-- COLD heightmap (mirror): ice core -> the snow rings, snow-flat outermost blending into
-- the flat cold outer (dust) slope. snow-patchy is the last DAMAGING cold ring.
M.COLD_RING_ORDER = {
  { vanilla = "ice-smooth",  lo = 140 },       -- frozen CORE / ocean peak
  { vanilla = "ice-rough",   lo = 95 },        -- rough ice, ringing the smooth cap
  { vanilla = "snow-patchy", lo = 60 },        -- snow (patchy), the last damaging ring
  { vanilla = "snow-lumpy",  lo = 30 },
  { vanilla = "snow-crests", lo = 5 },
  { vanilla = "snow-flat",   lo = -RING_BIG }, -- outermost, blends to the flat dust slope
}

-- SOIL patches: a mini ring model on a low-frequency PATCH field, confined to the middle
-- band. soil-dark at a patch centre, ringed by soil-light, then ash-soil, blending back
-- to the ash mix (E below the ash-soil band => no soil).
M.SOIL_RING_ORDER = {
  { vanilla = "volcanic-soil-dark",  lo = 20 },  -- patch centre (highest patch elevation)
  { vanilla = "volcanic-soil-light", lo = 14 },  -- ring around the dark core
  { vanilla = "volcanic-ash-soil",   lo = 8 },   -- outer ring, blends to the ash mix
}

-- FLAT-MIX zones (the safe outer slopes + the middle). Each lists its member tiles with a
-- weight at the band's HOT (hi) edge and COLD (lo) edge, linearly interpolated across the
-- band; a per-tile speckle interpenetrates co-present members -> an organic gradient.
local function m(vanilla, hot, cold) return { vanilla = vanilla, hot = hot, cold = cold } end
M.FLAT_ZONES = {
  -- hot outer slope [perp 60..130]: cracks-warm (blends to the heightmap at the hi edge)
  -- -> cracks -> smooth-stone -> ash-dark (blends to the middle at the lo edge).
  hot_outer = {
    m("volcanic-cracks-warm", 1, 0.15), m("volcanic-cracks", 0.5, 0.7),
    m("volcanic-smooth-stone", 0.3, 0.9), m("volcanic-ash-dark", 0, 0.5),
  },
  -- middle [perp -60..60]: the ash mix, even weights (soil is a separate patch ring).
  middle = {
    m("volcanic-ash-dark", 1, 1), m("volcanic-ash-light", 1, 1), m("volcanic-ash-flats", 1, 1),
  },
  -- cold outer slope [perp -130..-60]: ash-light (blends to the middle at the hi edge) ->
  -- dust-flat -> dust-crests -> dust-lumpy -> dust-patchy (blends to the snow heightmap at lo).
  cold_outer = {
    m("volcanic-ash-light", 0.5, 0), m("dust-flat", 0.9, 0.3), m("dust-crests", 0.7, 0.5),
    m("dust-lumpy", 0.4, 0.8), m("dust-patchy", 0.15, 1),
  },
}

-- ---------------------------------------------------------------------------
-- Per-TILE environmental damage (ci-4jl), scaling with depth (ci-wly).
-- ---------------------------------------------------------------------------
local function dmg(kind, intensity) return { kind = kind, intensity = intensity } end
M.TILE_DAMAGE_BY_VANILLA = {
  ["lava-hot"]                   = dmg("heat", 1.00), -- pure hot lava: peak burn
  ["lava"]                       = dmg("heat", 0.70), -- molten lava: high
  ["volcanic-smooth-stone-warm"] = dmg("heat", 0.45), -- warm stone ringing the lava: medium
  ["volcanic-cracks-hot"]        = dmg("heat", 0.30), -- glowing crust: medium-low
  ["volcanic-cracks-warm"]       = dmg("heat", 0.15), -- warm cracks: low (the edge-push margin)
  ["ice-smooth"]                 = dmg("cold", 1.00), -- the smooth-ice ocean: peak freeze
  ["ice-rough"]                  = dmg("cold", 0.50), -- rough ice: medium (the edge-push margin)
  ["snow-patchy"]                = dmg("cold", 0.20), -- the deepest snow ring: low
}

-- The NO-PAVE hazard set (ci-wly): the hottest / iciest hazards. Blocking paving here
-- keeps the lethal ground lethal and closes the ci-8vu lava-pump exploit.
M.NO_PAVE_VANILLA = {
  "lava-hot", "lava", "volcanic-smooth-stone-warm", "volcanic-cracks-hot",
  "ice-smooth", "ice-rough",
}

-- Impassable tiles: only the two lava tiles (molten fluid). smooth-ice is WALKABLE now.
local IMPASSABLE = { ["lava-hot"] = true, ["lava"] = true }

local TILE_DAMAGE = {}
for vanilla, d in pairs(M.TILE_DAMAGE_BY_VANILLA) do TILE_DAMAGE[cindra_name(vanilla)] = d end

M.NO_PAVE = {}
for _, vanilla in ipairs(M.NO_PAVE_VANILLA) do M.NO_PAVE[cindra_name(vanilla)] = true end

-- Damage INTENSITY (0..1) and KIND for a tile NAME, or (0, nil). Pure lookup.
function M.tile_damage(name)
  local d = TILE_DAMAGE[name]
  if d then return d.intensity, d.kind end
  return 0, nil
end

-- True if a tile is in the NO-PAVE hazard set (scripts/no-paving.lua reads this).
function M.is_no_pave(name) return M.NO_PAVE[name] == true end

-- ---------------------------------------------------------------------------
-- The concrete TILES (deduplicated), ordered hot -> cold, and the membership tables.
-- ---------------------------------------------------------------------------

-- A hot -> cold map-view colour ramp (ci-4h7): reds sunward, a dark ash belt at the
-- middle, pale cyan/frost nightward. `t` is the normalised gradient position (0 hottest,
-- 1 coldest). Kept in lockstep with gen-planet-maps.py.
local COLOR_STOPS = {
  { 0.00, { 0.98, 0.42, 0.06 } }, -- lava, orange-red
  { 0.18, { 0.80, 0.30, 0.10 } }, -- molten crust
  { 0.34, { 0.45, 0.32, 0.24 } }, -- warm volcanic brown (fire -> middle)
  { 0.46, { 0.243, 0.165, 0.125 } }, -- dark volcanic-ash middle #3E2A20
  { 0.54, { 0.255, 0.196, 0.157 } }, -- ash middle #41322A
  { 0.66, { 0.42, 0.42, 0.44 } }, -- cooling dust-grey (middle -> ice)
  { 0.80, { 0.66, 0.82, 0.88 } }, -- pale frost
  { 1.00, { 0.82, 0.95, 1.00 } }, -- icy white-blue
}
local function ramp_color(t)
  if t <= COLOR_STOPS[1][1] then return COLOR_STOPS[1][2] end
  for i = 2, #COLOR_STOPS do
    local a, b = COLOR_STOPS[i - 1], COLOR_STOPS[i]
    if t <= b[1] then
      local f = (t - a[1]) / (b[1] - a[1])
      local ca, cb = a[2], b[2]
      return { ca[1] + (cb[1] - ca[1]) * f, ca[2] + (cb[2] - ca[2]) * f, ca[3] + (cb[3] - ca[3]) * f }
    end
  end
  return COLOR_STOPS[#COLOR_STOPS][2]
end

M.TILES = {}
local TILE_BY_NAME = {}        -- cindra name -> tile entry
local HOT_RING_BAND = {}       -- cindra name -> { lo, hi } hot elevation band
local COLD_RING_BAND = {}      -- cindra name -> { lo, hi } cold elevation band
local SOIL_RING_BAND = {}      -- cindra name -> { lo, hi } soil patch band
local FLAT_MEMBER = {}         -- cindra name -> list of { role, hot, cold } flat-zone memberships
local GRADIENT_POS = {}        -- cindra name -> normalised 0..1 hot->cold position

local function build_bands(order, dst)
  local prev_hi = RING_BIG
  for _, r in ipairs(order) do
    dst[cindra_name(r.vanilla)] = { lo = r.lo, hi = prev_hi }
    prev_hi = r.lo
  end
end
build_bands(M.HOT_RING_ORDER, HOT_RING_BAND)
build_bands(M.COLD_RING_ORDER, COLD_RING_BAND)
build_bands(M.SOIL_RING_ORDER, SOIL_RING_BAND)
M.ring_band_hot = HOT_RING_BAND
M.ring_band_cold = COLD_RING_BAND

do
  local order = {}
  local function register(vanilla, gradient_pos)
    local name = cindra_name(vanilla)
    if not TILE_BY_NAME[name] then
      local entry = { name = name, clone_from = vanilla, walkable = not IMPASSABLE[vanilla] }
      TILE_BY_NAME[name] = entry
      order[#order + 1] = entry
      GRADIENT_POS[name] = gradient_pos
    elseif gradient_pos ~= nil and GRADIENT_POS[name] == nil then
      GRADIENT_POS[name] = gradient_pos
    end
    return name
  end

  -- Hot rings: gradient 0 (lava) -> ~0.40 (cracks-warm).
  local nh = #M.HOT_RING_ORDER
  for i, r in ipairs(M.HOT_RING_ORDER) do register(r.vanilla, 0.40 * (i - 1) / (nh - 1)) end
  -- Hot outer flat slope, then the middle mix + soil (the dark ash belt ~0.5).
  register("volcanic-cracks", 0.42); register("volcanic-smooth-stone", 0.45)
  register("volcanic-ash-dark", 0.47); register("volcanic-ash-flats", 0.50)
  register("volcanic-ash-light", 0.53)
  register("volcanic-ash-soil", 0.50); register("volcanic-soil-light", 0.50); register("volcanic-soil-dark", 0.50)
  -- Cold outer flat slope (dust), then the cold rings OUTER -> CORE (coldest last).
  register("dust-flat", 0.56); register("dust-crests", 0.58)
  register("dust-lumpy", 0.60); register("dust-patchy", 0.62)
  local nc = #M.COLD_RING_ORDER
  for i = nc, 1, -1 do register(M.COLD_RING_ORDER[i].vanilla, 1.0 - 0.40 * (i - 1) / (nc - 1)) end

  -- Build the flat-zone membership table.
  for role, members in pairs(M.FLAT_ZONES) do
    for _, mem in ipairs(members) do
      local name = cindra_name(mem.vanilla)
      register(mem.vanilla, GRADIENT_POS[name]) -- ensure registered (position already set above)
      FLAT_MEMBER[name] = FLAT_MEMBER[name] or {}
      FLAT_MEMBER[name][#FLAT_MEMBER[name] + 1] = { role = role, hot = mem.hot, cold = mem.cold }
    end
  end

  for _, entry in ipairs(order) do entry.map_color = ramp_color(GRADIENT_POS[entry.name] or 0.5) end
  M.TILES = order
end

-- Single-source-of-truth cross-checks.
for name in pairs(TILE_DAMAGE) do
  if not TILE_BY_NAME[name] then error("terrain: damage tile " .. name .. " is not a registered tile") end
end
for name in pairs(M.NO_PAVE) do
  if not TILE_BY_NAME[name] then error("terrain: no-pave tile " .. name .. " is not a registered tile") end
end

-- ---------------------------------------------------------------------------
-- Noise tuning.
-- ---------------------------------------------------------------------------
M.NOISE_AMPLITUDE = 2
M.NOISE_WAVELENGTH = 14
M.SPECKLE_AMPLITUDE = 1.5
M.SPECKLE_WAVELENGTH = 4
M.PLATEAU = 1000
M.WEIGHT_SCALE = 2

M.HEIGHT_AMPLITUDE = 55
M.HEIGHT_WAVELENGTH = 56
M.HEIGHT_BIAS = 115
M.RING_PLATEAU = 60
M.GATE_STEEP = 20
M.SEA_FILL = 200
M.SEA_WALL = 60

M.SOIL_AMPLITUDE = 26
M.SOIL_WAVELENGTH = 22
M.SOIL_PLATEAU = 8

M.HOT_GATE_STEEP = M.GATE_STEEP -- backwards-compat alias

-- The cindra tile a HOT elevation E falls in (pure). Off-game unit-testable.
function M.ring_tile_at(E)
  for _, r in ipairs(M.HOT_RING_ORDER) do
    if E >= r.lo then return cindra_name(r.vanilla) end
  end
  return nil
end
-- The cindra tile a COLD elevation E falls in.
function M.cold_ring_tile_at(E)
  for _, r in ipairs(M.COLD_RING_ORDER) do
    if E >= r.lo then return cindra_name(r.vanilla) end
  end
  return nil
end

local function num(v)
  if v == math.floor(v) then return string.format("%d", v) end
  return string.format("%.6g", v)
end

-- ---------------------------------------------------------------------------
-- Zone widths + band geometry (PURE).
-- ---------------------------------------------------------------------------
function M.widths(cfg)
  cfg = cfg or {}
  local s = settings and settings.startup
  local out = {}
  for i, z in ipairs(M.ZONES) do
    local w = cfg[z.role]
    if w == nil and s and s[z.setting] then w = s[z.setting].value end
    if w == nil then w = z.width end
    out[i] = w
  end
  return out
end

-- The signed perpendicular band [lo, hi] (sunward-positive p, hot = high p) per zone,
-- centred on the origin (hot edge +TOTAL/2). Returns (bands, total).
function M.bands(cfg)
  local w = M.widths(cfg)
  local total = 0
  for _, v in ipairs(w) do total = total + v end
  local bands = {}
  local p = total / 2
  for i = 1, #w do
    bands[i] = { lo = p - w[i], hi = p }
    p = p - w[i]
  end
  return bands, total
end

function M.role_band(role, cfg)
  local bands = M.bands(cfg)
  for i, z in ipairs(M.ZONES) do
    if z.role == role then return bands[i] end
  end
  return nil
end

-- The perpendicular band spanned by a set of regions = the union of their zone bands.
local function region_band(regions, cfg)
  local bands = M.bands(cfg)
  local lo, hi
  for i, z in ipairs(M.ZONES) do
    if regions[z.region] then
      if lo == nil or bands[i].lo < lo then lo = bands[i].lo end
      if hi == nil or bands[i].hi > hi then hi = bands[i].hi end
    end
  end
  return { lo = lo, hi = hi }
end

-- The perpendicular band spanned by the HOT heightmap (hot ocean + inner). The lava
-- heightmap/ring model is confined here; the bias ramps from 0 at the inner (middle-ward)
-- edge up to its peak at the ocean edge, where the solid sea is anchored.
function M.hot_region(cfg) return region_band({ hot = true }, cfg) end
-- The perpendicular band spanned by the COLD heightmap (cold inner + ocean).
function M.cold_region(cfg) return region_band({ cold = true }, cfg) end

local function ocean_band(region, cfg)
  local bands = M.bands(cfg)
  for i, z in ipairs(M.ZONES) do
    if z.region == region and z.ocean then return bands[i] end
  end
  return nil
end

-- The perp-axis boundaries scripts/resource-field.lua bands resources against.
function M.resource_bounds(cfg)
  local bands = M.bands(cfg)
  local b = bands[BUILDING_INDEX]
  local hot_edge = b.hi
  for i = BUILDING_INDEX - 1, 1, -1 do
    if not M.ZONES[i].wall then hot_edge = bands[i].hi else break end
  end
  return {
    building_half = b.hi,
    building_lo = b.lo,
    hot_edge = hot_edge,
    cold_edge = bands[#bands].lo,
  }
end

-- The perpendicular band spanned by the VOLCANIC rocky zones (hot inner + hot outer),
-- where burned volcanic rocks scatter. Excludes the lava ocean, middle and cold side.
M.CLIFF_ROLES = { "hot_inner", "hot_outer" }
function M.cliff_band(cfg)
  local lo, hi
  for _, role in ipairs(M.CLIFF_ROLES) do
    local b = M.role_band(role, cfg)
    if b then
      if lo == nil or b.lo < lo then lo = b.lo end
      if hi == nil or b.hi > hi then hi = b.hi end
    end
  end
  return { lo = lo, hi = hi }
end

-- The positional DAMAGE bounds (band edges where the damaging tiles live).
function M.damage_bounds(cfg)
  local bands = M.bands(cfg)
  local hot_from, cold_from
  for i, z in ipairs(M.ZONES) do
    if z.damage == "heat" then
      if hot_from == nil or bands[i].lo < hot_from then hot_from = bands[i].lo end
    elseif z.damage == "cold" then
      if cold_from == nil or bands[i].hi > cold_from then cold_from = bands[i].hi end
    end
  end
  return { hot_from = hot_from, cold_from = cold_from }
end

function M.lethal_at(p, cfg)
  local b = M.damage_bounds(cfg)
  if b.hot_from and p >= b.hot_from then return "heat" end
  if b.cold_from and p <= b.cold_from then return "cold" end
  return nil
end

-- ---------------------------------------------------------------------------
-- Noise-expression emitters.
-- ---------------------------------------------------------------------------
local function basis(seed1, amp, wl)
  return "basis_noise{x = x, y = y, seed0 = 1, seed1 = " .. num(seed1) ..
         ", input_scale = " .. num(1 / wl) .. ", output_scale = " .. num(amp) .. "}"
end
local function boundary_noise() return basis(7, M.NOISE_AMPLITUDE, M.NOISE_WAVELENGTH) end
local function speckle_noise(tile_index) return basis(100 + tile_index, M.SPECKLE_AMPLITUDE, M.SPECKLE_WAVELENGTH) end

local function relu(expr) return "max(0, " .. expr .. ")" end
local function clamp01(expr) return "min(1, max(0, " .. expr .. "))" end

-- One flat-band mix term for a tile's membership in a flat zone: a plateau that falls off
-- outside the band (keyed to the noise-wiggled perp axis P) + WEIGHT_SCALE * (weight
-- interpolated cold->hot across the band). `axis_expr` selects the axis (perp for hot/
-- middle, perp_neg for cold_outer would double the sign -- both use perp, since the band
-- geometry already carries the perp coordinates). Adjacent members mix via the speckle.
local function flat_band_term(mm, P, band)
  local span = math.max(1, band.hi - band.lo)
  local env = num(M.PLATEAU) .. " - (" .. relu(num(band.lo) .. " - " .. P) ..
              " + " .. relu(P .. " - " .. num(band.hi)) .. ")"
  local frac = clamp01("(" .. P .. " - " .. num(band.lo) .. ") / " .. num(span))
  local weight = num(M.WEIGHT_SCALE) .. " * (" .. num(mm.cold) ..
                 " + " .. num(mm.hot - mm.cold) .. " * " .. frac .. ")"
  return "(" .. env .. " + " .. weight .. ")"
end

-- One HEIGHTMAP RING term for a tile on one SIDE. gate confines the tile to the side's
-- span [reg_lo, reg_hi]; a ring selector picks the ring whose elevation band contains E.
-- E = the shared heightmap + a BIAS peaking at the ocean edge, with the ocean band's
-- elevation FORCED to SEA_FILL (a solid sea). `raw_axis` is the side's raw perpendicular
-- coordinate; `P` is that axis with the boundary wiggle.
local function side_ring_term(raw_axis, P, reg_lo, reg_hi, sea_anchor, band, seed)
  local out_span = math.max(1, sea_anchor - reg_lo)
  local gate = num(M.PLATEAU) .. " - " .. num(M.GATE_STEEP) .. " * (" ..
               relu(num(reg_lo) .. " - " .. P) .. " + " .. relu(P .. " - " .. num(reg_hi)) .. ")"
  local bias = num(M.HEIGHT_BIAS) .. " * " ..
               clamp01("(" .. P .. " - " .. num(reg_lo) .. ") / " .. num(out_span))
  local E_base = "(" .. basis(seed, M.HEIGHT_AMPLITUDE, M.HEIGHT_WAVELENGTH) .. " + " .. bias .. ")"
  local sea_floor = num(M.SEA_FILL) .. " - " .. num(M.SEA_WALL) .. " * " ..
                    relu(num(sea_anchor) .. " - (" .. raw_axis .. ")")
  local E = "max(" .. E_base .. ", " .. sea_floor .. ")"
  local elev = num(M.RING_PLATEAU) .. " - (" .. relu(num(band.lo) .. " - " .. E) ..
               " + " .. relu(E .. " - " .. num(band.hi)) .. ")"
  return "(" .. gate .. " + " .. elev .. ")"
end

-- One SOIL patch ring term: a mini ring on a low-frequency PATCH field, confined to the
-- middle band, with a MODEST plateau so a soil ring only wins where the patch field is
-- inside its band (a patch), never across the whole middle.
local function soil_ring_term(P, mid_band, band)
  local gate = num(M.PLATEAU) .. " - " .. num(M.GATE_STEEP) .. " * (" ..
               relu(num(mid_band.lo) .. " - " .. P) .. " + " .. relu(P .. " - " .. num(mid_band.hi)) .. ")"
  local E = basis(50, M.SOIL_AMPLITUDE, M.SOIL_WAVELENGTH)
  local elev = num(M.SOIL_PLATEAU) .. " - (" .. relu(num(band.lo) .. " - " .. E) ..
               " + " .. relu(E .. " - " .. num(band.hi)) .. ")"
  return "(" .. gate .. " + " .. elev .. ")"
end

-- The `probability_expression` for a Cindra tile: the MAX over its terms + a speckle. A
-- tile can carry a HOT ring term, a COLD ring term, one or more FLAT-zone terms, and/or a
-- SOIL ring term. The engine places the highest-probability tile per point.
function M.probability_expr(name, cfg)
  local tile, index
  for i, t in ipairs(M.TILES) do
    if t.name == name then tile = t; index = i; break end
  end
  if not tile then error("terrain: unknown Cindra tile " .. tostring(name)) end

  local bands = M.bands(cfg)
  local mid_band = bands[BUILDING_INDEX]
  local P = "(" .. axis.perp_expr() .. " + " .. boundary_noise() .. ")"
  local terms = {}

  local hband = HOT_RING_BAND[name]
  if hband then
    local hr = M.hot_region(cfg)
    local sea = ocean_band("hot", cfg)
    terms[#terms + 1] = side_ring_term(axis.perp_expr(), P, hr.lo, hr.hi, sea.lo, hband, 42)
  end

  local cband = COLD_RING_BAND[name]
  if cband then
    local cr = M.cold_region(cfg)
    local sea = ocean_band("cold", cfg)
    local q = axis.perp_neg_expr()
    local Q = "(" .. q .. " + " .. boundary_noise() .. ")"
    -- In nightward q-space: region [ -cr.hi, -cr.lo ], sea anchor = -sea.hi (ocean inner edge).
    terms[#terms + 1] = side_ring_term(q, Q, -cr.hi, -cr.lo, -sea.hi, cband, 43)
  end

  for _, mm in ipairs(FLAT_MEMBER[name] or {}) do
    terms[#terms + 1] = flat_band_term(mm, P, M.role_band(mm.role, cfg))
  end

  local sband = SOIL_RING_BAND[name]
  if sband then
    terms[#terms + 1] = soil_ring_term(P, mid_band, sband)
  end

  if #terms == 0 then error("terrain: tile " .. name .. " has no placement term") end
  local expr = terms[1]
  for i = 2, #terms do expr = "max(" .. expr .. ", " .. terms[i] .. ")" end
  return "(" .. expr .. ") + " .. speckle_noise(index)
end

function M.map_color(name)
  local t = TILE_BY_NAME[name]
  return t and t.map_color or nil
end

function M.is_walkable(name)
  local t = TILE_BY_NAME[name]
  if t == nil then return nil end
  return t.walkable
end

-- The set of member tile names (cindra-*) of a zone role, as a set { name = true }: the
-- tiles a point in that zone's band can be painted with.
function M.zone_tiles(role)
  local out = {}
  local zone
  for _, z in ipairs(M.ZONES) do if z.role == role then zone = z end end
  if not zone then return out end
  if zone.region == "hot" then
    for _, r in ipairs(M.HOT_RING_ORDER) do out[cindra_name(r.vanilla)] = true end
  elseif zone.region == "cold" then
    for _, r in ipairs(M.COLD_RING_ORDER) do out[cindra_name(r.vanilla)] = true end
  else -- a flat zone (hot_flat / middle / cold_flat)
    for _, mem in ipairs(M.FLAT_ZONES[role] or {}) do out[cindra_name(mem.vanilla)] = true end
    if zone.region == "middle" then
      for _, r in ipairs(M.SOIL_RING_ORDER) do out[cindra_name(r.vanilla)] = true end
    end
  end
  return out
end

function M.tile_zones(name)
  local out = {}
  for _, z in ipairs(M.ZONES) do
    if M.zone_tiles(z.role)[name] then out[z.role] = true end
  end
  return out
end

function M.tile_names()
  local out = {}
  for _, t in ipairs(M.TILES) do out[#out + 1] = t.name end
  return out
end

function M.finite_dimension(cfg)
  local _, total = M.bands(cfg)
  return {
    key = (axis.orientation() == axis.HORIZONTAL) and "height" or "width",
    value = total,
  }
end

return M
