-- Cindra ice processing (§15-4; DESIGN.md §1 "nightward edge = MATTER", §5a).
--
-- The nightside's matter economy is now split at the SOURCE: mining an ice field
-- yields a FIXED MIX of `ice` + `calcite` directly (ci-9l6, see resources.lua) --
-- there is no feedstock chunk and no ground crusher any more. `calcite` is a native
-- mined resource (the aluminium refine, the science pack, and the ci-400
-- calcite->olefins chain consume it); `ice` still becomes the factory's `water`.
--
-- So the ONLY processing step left on the nightside is the MELT, and it REUSES the
-- vanilla Space Age recipe end-to-end (ci-3mx: "the existing ice melting in the
-- chemical plant", "stop adding equivalent technologies"):
--
--   MELT (vanilla `chemistry` category) -- the vanilla `ice-melting` recipe in the
--   vanilla CHEMICAL PLANT turns `ice` into `water`. No custom melter (the vanilla
--   chemical plant stands on any gravity), no custom item, no dedicated ice tech,
--   and `chemistry` holds no exploitable recipe so it needs no private category.
--
-- 🚨 WHY NO GROUND CRUSHER ANY MORE (ci-9l6, supersedes ci-3mx/ci-8n6):
-- the old design mined an `oxide-asteroid-chunk` and crushed it on a cloned
-- ground crusher (chunk -> ice, or chunk -> ice + calcite). ci-9l6 moves the mix
-- to the MINING DRILL itself, so the crusher's only job (chunk -> ice) is gone and
-- the crusher, its build recipe, the two Cindra oxide-crushing recipes, and the
-- dedicated `cindra-crushing` category are all RETIRED. The ci-8n6 economy exploit
-- (reprocess oxide chunks -> metallic/carbonic -> free iron/coal on a ground
-- crusher) is now closed BY CONSTRUCTION: Cindra has no ground crushing machine and
-- no oxide chunk to crush, so no free-metal/coal path can exist. A reachability
-- GUARD in tests/test_ice_processing.lua asserts this stays true.
--
-- The `ice` this chain melts is also the science pack's nightside input
-- (prototypes/science.lua): the deep-nightside ice field is the worked,
-- petrochemical-free cold-edge feedstock for the headline pack, reachable with the
-- rest of the chain via the same planet-discovery-cindra unlocks.
--
-- WHY NO CINDRA ICE TECH: the melt is unlocked by the EXISTING
-- `planet-discovery-cindra` tech (we append the unlock effect below). In normal
-- play you research discovery to reach Cindra; on an any-planet-start Cindra run
-- APS removes that tech and enables its unlocked recipes from tick zero
-- (vendor/any-planet-start/data-final-fixes.lua), so the chain works on both paths
-- with no new/equivalent technology.

-- === Unlock the melt via the existing Cindra discovery tech (no new tech) =======
-- Append the ice-melt unlock to `planet-discovery-cindra` (defined in planet.lua,
-- required before this file). Normal play: researching discovery unlocks it. APS
-- Cindra-start: APS removes this tech and enables its unlocked recipes from tick
-- zero (data-final-fixes.lua), so the melt works there too. Unlocking the vanilla
-- `ice-melting` recipe for the force does NOT mutate it or any other planet's
-- content (§6) -- we only reference it in an unlock effect.
local discovery = data.raw.technology["planet-discovery-cindra"]
assert(discovery, "planet-discovery-cindra must be defined before ice-processing")
table.insert(discovery.effects, { type = "unlock-recipe", recipe = "ice-melting" })
