-- The Cindra planet (§1, §2, §4; §15 item 1).
--
-- Minimal-but-real: a valid, LOADABLE, LANDABLE planet so `surface.name ==
-- "cindra"` exists in a live game and the ribbon/temperature systems actually
-- run on it. Cindra is tidally locked and orbits perilously close to its star:
-- a molten dayside, a frozen nightside, and a narrow survivable ribbon at the
-- terminator (the playable surface). Its identity is a single tension — HOT vs
-- COLD — and survival is routing the star's surplus between fire and ice.
--
-- v1 ART NOTE (see TODO.md / PLAYTEST.md): custom Cindra sprites (star-map,
-- orbital backdrop, terminator terrain) are DEFERRED. To keep the planet
-- loadable now we reference vanilla Vulcanus icons (a hot, sunward-facing world
-- reads correctly for the dayside). The bespoke ribbon art is a later art pass;
-- gameplay does not depend on it.
--
-- DEFERRED to §15 item 2 (documented, not a gap): the PHYSICAL ribbon geometry
-- (impassable hard-wall backstop perpendicular to the terminator, generous
-- east-west length). This file establishes the planet + surface + the
-- temperature axis framing; scripts/ribbon.lua is the single source of truth for
-- the hot-cold axis value (unit-tested). The lethal-edge damage that CONSUMES
-- that axis, and the wall that bounds it, land in item 2.

local asteroid_util = require("__space-age__.prototypes.planet.asteroid-spawn-definitions")
local space = require("prototypes.space-appearance")
local terrain = require("scripts.terrain")
local field = require("scripts.resource-field")

local minute = 60 * 60

-- Star-map placement + tidal-lock presentation (ci-2sr).
--
-- Cindra hugs the star: a small orbital radius so it sits well sunward of
-- Vulcanus (distance 10), the innermost world of the system. ci-bu4: was 3, which
-- planted the globe INSIDE the sun disc at the map centre. Pull it back out to a
-- clear orbit that still reads as the closest world to the star (distance 6, the
-- pre-ci-2sr clear position; the drop to 3 overshot).
local ORBIT_DISTANCE = 6
-- Angular position on the orbit ring (RealOrientation: 0 = up, clockwise).
local ORBIT_ORIENTATION = 0.05
-- TIDAL LOCK: the fiery dayside must face the star. The star-map icon is a fixed
-- bake (space-appearance.lua) with the FIRE hemisphere on the sprite's LEFT limb
-- and the icy nightside on the right. starmap_icon_orientation defaults to
-- "aim the icon's TOP at the sun", which leaves that fiery LEFT limb a quarter-
-- turn (~90deg) off the sunward line -- exactly the "rotated wrong" the report
-- flags. Rotate the icon a quarter-turn so the FIRE limb, not the top, points at
-- the star. Still a single fixed value: tidal lock, the globe never spins.
local STARMAP_ICON_ORIENTATION = (ORBIT_ORIENTATION - 0.25) % 1
-- TIDAL LOCK => NO day/night cycle. Express that as an effectively-infinite cycle
-- length so the map view reads "no cycle" (an enormous number of minutes), NOT 0:
-- a 0 flips the surface to always_day and flattens the daylight curve that
-- scripts/flare.lua rides to swing solar output between flares. A huge finite
-- value keeps that curve intact while making the cycle imperceptible (the flare
-- driver freezes daytime anyway). Mirrors the NO_ROTATION trick space-appearance
-- uses to freeze the globe.
local NO_DAY_NIGHT_CYCLE = 300000 * minute

-- Cindra terrain: a REAL ribbon planet generated by the MAP-GEN itself (ci-3yl),
-- NOT a Nauvis map patched by an on_chunk_generated script.
--
--   * FINITE PERPENDICULAR: the map-gen's own `width` (vertical orientation) bounds
--     the ribbon on the hot-cold axis, so the engine fills everything beyond the
--     band with `out-of-map` -- the void backstop emerges from the map-gen, no
--     script deletes chunks. Infinite along the ribbon's long axis. NOTE: the
--     engine IGNORES width/height on a planet PROTOTYPE's map_gen_settings, so the
--     value set here documents intent; scripts/driver.enforce_finite applies it to
--     the surface the moment it is created (a one-time map-gen config, still no
--     per-chunk void surgery).
--   * NOISE-DRIVEN TILE BANDS: the ground is Cindra's OWN `cindra-*` tiles
--     (prototypes/tiles.lua), each placed by a noise expression keyed to the
--     perpendicular axis (scripts/terrain.lua). Band boundaries carry a smooth
--     basis-noise wiggle, so they are ORGANIC curves, never raw straight lines.
--   * ZERO NAUVIS LEAKAGE: only Cindra tiles are placement candidates -- NO grass,
--     no water, no vanilla terrain. No trees / enemies / rocks / cliffs / decoratives.
--   * ELEVATION: pinned flat (prototypes/noise.lua) so no lake is ever carved.
--
-- Resources (stone + ice) and the finite bootstrap rocks are NATIVE autoplace
-- (prototypes/resources.lua), banded to the ribbon and surfacing real Frequency/
-- Size/Richness sliders -- grouped below Aquilo on the map-gen screen, Stone + Ice
-- only (the standalone volatiles resource is gone; volatiles come from the ice chain).
local function cindra_map_gen()
  local finite = terrain.finite_dimension()

  local tile_settings = {}
  for _, name in ipairs(terrain.tile_names()) do tile_settings[name] = {} end

  -- The entity autoplace allow-list: ONLY these Cindra entities generate (with
  -- treat_missing_as_default = false, an entity absent here never autoplaces). The
  -- resources + the finite bootstrap rocks, plus the hot-region burned volcanic
  -- rocks (ci-qy0). Names come from scripts/resource-field.lua so this list can
  -- never drift from the prototypes it gates.
  local entity_autoplace_settings = {
    [field.STONE] = {},
    [field.ICE] = {},
    [field.ROCK] = {},
  }
  for _, name in ipairs(field.burned_rock_names()) do
    entity_autoplace_settings[name] = {}
  end

  local mg = {
    -- Finite perpendicular to the ribbon (the ribbon planet), infinite lateral.
    [finite.key] = finite.value,
    -- Named noise expression: flat land everywhere (no lakes), the generic
    -- terrain property Cindra overrides (prototypes/noise.lua).
    property_expression_names = {
      elevation = "cindra_ribbon_elevation",
    },
    -- ONLY Cindra's own resource controls -> the map-gen screen shows just Stone
    -- and Ice (ordered below Aquilo, see prototypes/resources.lua). No Nauvis
    -- water / moisture / starting-moisture / terrain-type sliders.
    default_enable_all_autoplace_controls = false,
    autoplace_controls = {
      ["cindra-stone"] = {},
      ["cindra-ice"] = {},
    },
    autoplace_settings = {
      -- Tiles: ONLY Cindra tiles are candidates. No grass, no water, no Nauvis
      -- tile can ever be placed (they are not in the set).
      tile = { treat_missing_as_default = false, settings = tile_settings },
      -- Entities: only the Cindra resources + the finite rocks autoplace.
      entity = {
        treat_missing_as_default = false,
        settings = entity_autoplace_settings,
      },
      -- No decoratives (no Nauvis grass tufts etc.).
      decorative = { treat_missing_as_default = false, settings = {} },
    },
    -- No cliffs (push the elevation threshold out of reach; no cliff control).
    cliff_settings = { name = "cliff", cliff_elevation_0 = 1024, cliff_elevation_interval = 1024 },
  }

  return mg
end

data:extend({
  {
    type = "planet",
    name = "cindra",
    -- Map name/description (ci-2sr). Pin the localised name to the plain
    -- "space-location-name.cindra" ("Cindra") so the map view reads just "Cindra"
    -- (no tagline in the user-facing name),
    -- and give it a real planet description like the vanilla planets do.
    localised_name = { "space-location-name.cindra" },
    localised_description = { "space-location-description.cindra" },
    -- v1: vanilla Vulcanus art (see ART NOTE above). data-updates.lua swaps in the
    -- baked Cindra icon + star-map sprite (ci-94v); these are the load-time
    -- placeholders it overrides.
    icon = "__space-age__/graphics/icons/vulcanus.png",
    icon_size = 64,
    icon_mipmaps = 4,
    starmap_icon = "__space-age__/graphics/icons/starmap-planet-vulcanus.png",
    starmap_icon_size = 512,
    gravity_pull = 10,
    -- Innermost world of the system: Cindra hugs the star, sunward of Vulcanus.
    distance = ORBIT_DISTANCE,
    orientation = ORBIT_ORIENTATION,
    -- Tidal lock: point the baked fiery dayside at the star (see above).
    starmap_icon_orientation = STARMAP_ICON_ORIENTATION,
    magnitude = 1.2,
    order = "a[cindra]",
    subgroup = "planets",
    map_gen_settings = cindra_map_gen(),
    pollutant_type = nil,
    -- Orbits perilously close to the star -> the strongest orbit solar in the
    -- system: 1000, well above Vulcanus's 600 (Nauvis 300). Platforms parked over
    -- Cindra bake in the light. (Was 2000; halved per ci-2sr.)
    solar_power_in_space = 1000,
    surface_properties = {
      -- TIDAL LOCK => no day/night cycle: an effectively-infinite length so the
      -- map view reports no cycle. NOT 0 (that would flatten the daylight curve
      -- the flare driver rides). See NO_DAY_NIGHT_CYCLE above.
      ["day-night-cycle"] = NO_DAY_NIGHT_CYCLE,
      ["magnetic-field"] = 25,
      -- §15-7 solar: the real ~10000%-of-Nauvis surface multiplier (100x). Nauvis
      -- reads 100 here; 10000 = 100x, the fixed high multiplier the flare swings
      -- across via the daylight curve. scripts/flare.lua re-affirms the matching
      -- surface.solar_power_multiplier at runtime as it drives the curve, and the
      -- dim between-flare floor still delivers a 400 kW baseline (ci-ezk: > Vulcanus's
      -- 240 kW, runs the factory). (tune) §15-14 validates this against the lava cost.
      ["solar-power"] = 10000,
      -- No atmosphere to speak of ("the air itself would boil, were there any"):
      -- a thin envelope over molten rock.
      pressure = 500,
      gravity = 20,
    },
    -- No custom orbital backdrop / clouds in v1 (art deferred). The engine
    -- renders a plain approach; the planet is fully playable without it.
  },
  -- Reachability (§6): Cindra is GATED AFTER VULCANUS — you need foundries +
  -- lava-processing tech before the manufactured-lava economy makes sense.
  -- Hang it off Vulcanus (both hot, sunward worlds), reached after it.
  {
    type = "space-connection",
    name = "vulcanus-cindra",
    subgroup = "planet-connections",
    from = "vulcanus",
    to = "cindra",
    order = "a[cindra]",
    -- ci-2sr: was 80000 (~5x the vanilla inter-planet norm, an absurd haul). The
    -- other connections are ~15000; Cindra now hugs the star just inside Vulcanus,
    -- so the hop is SHORT. 12000 (a touch under the norm) reads as "next door".
    length = 12000,
    -- Route icon (ci-2sr, reworked ci-bu4): match the vanilla route-icon
    -- convention exactly -- transfer-arrow base, origin badge top-left,
    -- destination badge bottom-right and frontmost, both badges the same size.
    -- See space.route_icons: the vanilla auto-composite would bake the Vulcanus
    -- placeholder as Cindra (its data-updates runs before ours swaps the icon), so
    -- we pin the same composite by hand with the real baked Cindra icon.
    icons = space.route_icons(),
    -- Space-connection form: the helper takes NO density multiplier (that second
    -- arg is for a planet's approach field, and yields a different structure).
    -- ci-bu4: was nauvis_vulcanus, which gave the hop a Nauvis-tier asteroid field
    -- (dense metallic chunks). This leg leaves Vulcanus for a hot inner world, so
    -- carry the Vulcanus/Gleba-tier field -- the same mix vanilla's Vulcanus->Gleba
    -- route uses (test_planet.lua compares them byte-for-byte).
    asteroid_spawn_definitions = asteroid_util.spawn_definitions(asteroid_util.vulcanus_gleba),
  },
  -- Discovery tech: without an unlock-space-location effect Cindra shows up
  -- greyed-out (visible but not travellable) on the star map. Gated behind
  -- Vulcanus per §6. (When a game STARTS on Cindra via any-planet-start, that
  -- mod removes this tech and unlocks the location directly.)
  {
    type = "technology",
    name = "planet-discovery-cindra",
    icon = "__space-age__/graphics/icons/vulcanus.png",
    icon_size = 64,
    icon_mipmaps = 4,
    essential = true,
    effects = {
      { type = "unlock-space-location", space_location = "cindra", use_icon_overlay_constant = true },
    },
    prerequisites = { "planet-discovery-vulcanus" },
    unit = {
      count = 500,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
        { "space-science-pack", 1 },
      },
      time = 60,
    },
  },
})
