-- Proof: Cindra is a REAL ribbon planet generated by the MAP-GEN itself, a THREE-PART
-- TWO-HEIGHTMAP world (ci-3yl worldgen; ci-wly rebuild).
--
-- No on_chunk_generated script paints or voids anything. This drives the actual planet
-- map_gen_settings on a fresh, fixed-seed surface and proves, on the default vertical
-- orientation (ribbon long axis = Y; hot-cold gradient = X, hot on the LEFT / west,
-- perp = -x):
--   1. FINITE PERPENDICULAR: width = SUM of the zone widths (800) voids beyond the band.
--   2. TWO INTEGRATED OCEANS: the sunward hot-lava ocean AND the nightward smooth-ice
--      ocean each generate as a SOLID contiguous sea at the map edge, seed-independent,
--      FOLDED INTO the heightmap (never stamped on top).
--   3. HEIGHTMAP RINGS: lava/ice sit in pools ringed by their crust; each ocean thins
--      toward the habitable middle.
--   4. THREE REGIONS: the hot slope is hot-family tiles, the middle is the ash mix +
--      soil, the cold slope is cold-family tiles; the families never cross the middle.
--   4a. THE HOT-SIDE FOLDS BRANCH (ci-72bw): the safe hot slope carries TWO texture
--      families (cracks and folds/pumice) over the same value segment, picked per-REGION
--      by a low-frequency selector; both converge on ash-dark and neither leaks out.
--   5. WALKABILITY: only the two lava tiles are impassable; smooth-ice is now WALKABLE.
--   6. DAMAGE: positional -- the hot ocean+inner burn, the cold inner+ocean freeze.
--   7. ZERO NAUVIS LEAKAGE. 8. NATIVE RESOURCES banded. 9. NO CLIFFS. 10. LANDABLE.
--
-- The pure zone geometry is proven in unit-tests/test_terrain + test_resource_field;
-- this proves it actually generates on a live surface.

local field = require("scripts.resource-field")
local terrain = require("scripts.terrain")
local tile_damage = require("scripts.tile-damage")

describe("cindra worldgen: a three-part two-heightmap ribbon planet (§4; ci-wly)", function()
  local s
  local ready = false
  local RY = 350

  before_each(function()
    if ready then return end
    local base = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local mgs = base.map_gen_settings
    mgs.seed = 2468
    local fd = terrain.finite_dimension()
    mgs[fd.key] = fd.value
    s = game.surfaces["cindra-worldgen-test"] or game.create_surface("cindra-worldgen-test", mgs)
    -- Radius 15 chunks (~480 tiles) covers the full x in [-400,400] out to y ~= +/-RY.
    s.request_to_generate_chunks({ 0, 0 }, 15)
    s.force_generate_chunk_requests()
    ready = true
  end)

  local function tile(x, y) return s.get_tile(x, y).name end

  local HOT_FAMILY, MIDDLE_FAMILY, COLD_FAMILY = {}, {}, {}
  for _, v in ipairs({ "lava-hot", "lava", "volcanic-smooth-stone-warm", "volcanic-cracks-hot",
                       "volcanic-cracks-warm", "volcanic-cracks", "volcanic-smooth-stone", "volcanic-ash-dark",
                       -- the ci-72bw folds branch: the hot slope's ALTERNATE texture family
                       "volcanic-folds-warm", "volcanic-folds", "volcanic-folds-flat",
                       "volcanic-ash-cracks", "volcanic-pumice-stones" }) do
    HOT_FAMILY["cindra-" .. v] = true
  end
  -- The two hot-slope families (ci-72bw), read from the single source of truth.
  local FOLDS = terrain.family_tiles("folds")
  local CRACKS = terrain.family_tiles("cracks")
  for _, v in ipairs({ "volcanic-ash-dark", "volcanic-ash-light", "volcanic-ash-flats",
                       "volcanic-ash-soil", "volcanic-soil-light", "volcanic-soil-dark" }) do
    MIDDLE_FAMILY["cindra-" .. v] = true
  end
  for _, v in ipairs({ "ice-smooth", "ice-rough", "snow-patchy", "snow-lumpy", "snow-crests", "snow-flat",
                       "dust-patchy", "dust-lumpy", "dust-crests", "dust-flat", "volcanic-ash-light" }) do
    COLD_FAMILY["cindra-" .. v] = true
  end
  local LAVA = { ["cindra-lava-hot"] = true, ["cindra-lava"] = true }
  local HOT_CRUST = {
    ["cindra-volcanic-cracks-hot"] = true, ["cindra-volcanic-cracks-warm"] = true,
    ["cindra-volcanic-smooth-stone-warm"] = true,
  }
  local COLD_RING = {}
  for _, v in ipairs({ "ice-rough", "snow-patchy", "snow-lumpy", "snow-crests", "snow-flat" }) do
    COLD_RING["cindra-" .. v] = true
  end

  local function count_in(names_set, x1, x2, y1, y2)
    local n = 0
    for _, name in ipairs(terrain.tile_names()) do
      if names_set[name] then n = n + s.count_tiles_filtered({ name = name, area = { { x1, y1 }, { x2, y2 } } }) end
    end
    return n
  end

  -- 1. FINITE PERPENDICULAR --------------------------------------------------------
  it("is finite perpendicular: the map-gen voids beyond the total width (800), interior playable", function()
    assert.are.equal("out-of-map", tile(-410, 0), "sunward (west) beyond the ribbon is void")
    assert.are.equal("out-of-map", tile(410, 0), "nightward (east) beyond the ribbon is void")
    assert.are_not.equal("out-of-map", tile(0, 0), "the middle centre is playable")
    assert.are_not.equal("out-of-map", tile(-390, 0), "the hot-lava ocean edge is still land")
    assert.are_not.equal("out-of-map", tile(390, 0), "the ice ocean edge is still land")
  end)

  -- 2. TWO INTEGRATED, SOLID OCEANS ------------------------------------------------
  it("generates a SOLID hot-lava OCEAN at the sunward edge, zero gaps (ci-wly)", function()
    -- hot ocean band perp [200,400] -> x in [-400,-200]. Scan the interior.
    local box = { { -396, -RY }, { -204, RY } }
    local gaps = 0
    for _, name in ipairs(terrain.tile_names()) do
      if name ~= "cindra-lava-hot" then gaps = gaps + s.count_tiles_filtered({ name = name, area = box }) end
    end
    assert.are.equal(0, gaps, "the hot-lava ocean is a SOLID sea (found " .. gaps .. " non-lava-hot tiles)")
    assert.is_true(s.count_tiles_filtered({ name = "cindra-lava-hot", area = box }) > 1000, "large contiguous lava ocean")
  end)

  it("generates a SOLID smooth-ice OCEAN at the nightward edge -- INTEGRATED, not stamped (ci-wly/ci-7jc)", function()
    -- ice ocean band perp [-400,-200] -> x in [200,400]. The KEYSTONE cold-side fix: the
    -- ice ocean is the elevation PEAK of the cold heightmap, NOT a rectangle stamped over
    -- a finished map -- so it has no gaps and rings radiate inward from it.
    local box = { { 204, -RY }, { 396, RY } }
    local gaps = 0
    for _, name in ipairs(terrain.tile_names()) do
      if name ~= "cindra-ice-smooth" then gaps = gaps + s.count_tiles_filtered({ name = name, area = box }) end
    end
    assert.are.equal(0, gaps, "the smooth-ice ocean is a SOLID sea (found " .. gaps .. " non-ice-smooth tiles)")
    assert.is_true(s.count_tiles_filtered({ name = "cindra-ice-smooth", area = box }) > 1000, "large contiguous ice ocean")
  end)

  it("keeps BOTH oceans solid on OTHER seeds (seed-independent, ci-wly)", function()
    local base = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local fd = terrain.finite_dimension()
    for _, seed in ipairs({ 111, 99999 }) do
      local mgs = base.map_gen_settings
      mgs.seed = seed
      mgs[fd.key] = fd.value
      local sname = "cindra-ocean-seed-" .. seed
      local ss = game.surfaces[sname] or game.create_surface(sname, mgs)
      ss.request_to_generate_chunks({ 0, 0 }, 15)
      ss.force_generate_chunk_requests()
      local function gaps_in(core, x1, x2)
        local g = 0
        for _, name in ipairs(terrain.tile_names()) do
          if name ~= core then g = g + ss.count_tiles_filtered({ name = name, area = { { x1, -100 }, { x2, 100 } } }) end
        end
        return g
      end
      assert.are.equal(0, gaps_in("cindra-lava-hot", -396, -204), "seed " .. seed .. ": the lava ocean is still solid")
      assert.are.equal(0, gaps_in("cindra-ice-smooth", 204, 396), "seed " .. seed .. ": the ice ocean is still solid")
    end
  end)

  -- 3. HEIGHTMAP RINGS -------------------------------------------------------------
  it("rings every lava pool with hot crust: lava never directly touches non-hot terrain", function()
    local ring_smooth, ring_other, leaks, lava_seen = 0, 0, 0, 0
    for x = -396, -135, 1 do
      for y = -150, 150, 3 do
        if LAVA[tile(x, y)] then
          lava_seen = lava_seen + 1
          for _, d in ipairs({ { 1, 0 }, { -1, 0 }, { 0, 1 }, { 0, -1 } }) do
            local n = tile(x + d[1], y + d[2])
            if not LAVA[n] then
              if n == "cindra-volcanic-smooth-stone-warm" then ring_smooth = ring_smooth + 1
              elseif HOT_CRUST[n] then ring_other = ring_other + 1
              else leaks = leaks + 1 end
            end
          end
        end
      end
    end
    assert.is_true(lava_seen > 50, "sampled a meaningful amount of lava (" .. lava_seen .. ")")
    assert.are.equal(0, leaks, "lava is always insulated by its hot-crust rings (leaks=" .. leaks .. ")")
    assert.is_true(ring_smooth >= ring_other, "the immediate ring around lava is predominantly smooth-stone-warm")
  end)

  it("rings the smooth-ice pools with cold crust: ice never directly touches middle/hot terrain", function()
    local ring, leaks, ice_seen = 0, 0, 0
    for x = 135, 396, 1 do
      for y = -150, 150, 3 do
        if tile(x, y) == "cindra-ice-smooth" then
          ice_seen = ice_seen + 1
          for _, d in ipairs({ { 1, 0 }, { -1, 0 }, { 0, 1 }, { 0, -1 } }) do
            local n = tile(x + d[1], y + d[2])
            if n ~= "cindra-ice-smooth" then
              if COLD_RING[n] then ring = ring + 1 else leaks = leaks + 1 end
            end
          end
        end
      end
    end
    assert.is_true(ice_seen > 50, "sampled a meaningful amount of smooth ice (" .. ice_seen .. ")")
    assert.are.equal(0, leaks, "smooth-ice is always insulated by its cold rings (leaks=" .. leaks .. ")")
    assert.is_true(ring > 0, "smooth-ice pools are bounded by rough-ice / snow rings")
  end)

  it("gates both oceans by the gradient: dense at the map edge, thinning toward the middle", function()
    local lava_edge = count_in(LAVA, -396, -204, -RY, RY)
    local lava_mid = count_in(LAVA, -175, -135, -RY, RY)
    assert.is_true(lava_edge > lava_mid * 3, "lava thins toward the middle (edge=" .. lava_edge .. ", mid=" .. lava_mid .. ")")
    local ice_edge = s.count_tiles_filtered({ name = "cindra-ice-smooth", area = { { 204, -RY }, { 396, RY } } })
    local ice_mid = s.count_tiles_filtered({ name = "cindra-ice-smooth", area = { { 135, -RY }, { 175, RY } } })
    assert.is_true(ice_edge > ice_mid * 3, "smooth-ice thins toward the middle (edge=" .. ice_edge .. ", mid=" .. ice_mid .. ")")
  end)

  -- 4. THREE REGIONS ---------------------------------------------------------------
  -- Each region still READS as its own family, but it is no longer a pure one. The
  -- cosmetic scatter (ci-frcw) drops occasional patches of a neighbour's tile into it, on
  -- purpose -- ci-oe83 sanctioned exactly that soft bleed ("tiles MAY bleed/blend
  -- softly") to kill the three-stacked-bands look. So what is asserted is what a player
  -- actually reads: the region is DOMINATED by its own family, and every tile that bled
  -- in is COSMETIC ONLY -- harmless, walkable ground, never an ocean tile. The hard
  -- guards live below (no damaging ground in the safe corridor) and in test_heightmap
  -- (the belts stay unbypassable, the middle stays traversable).
  local function census(family, x1, x2)
    local own, bled, examples = 0, 0, {}
    for _, y in ipairs({ -120, -60, 0, 60, 120 }) do
      for x = x1, x2 do
        local n = tile(x, y)
        if family[n] then
          own = own + 1
        else
          bled = bled + 1
          examples[n] = (examples[n] or 0) + 1
          -- THE hard half: a bled tile must be pure decoration.
          local intensity = terrain.tile_damage(n)
          assert.are.equal(0, intensity,
            "a tile bled into a neighbouring region must be harmless; " .. n .. " at (" .. x .. "," .. y .. ")")
          assert.is_true(terrain.is_walkable(n) == true,
            "a tile bled into a neighbouring region must be walkable; " .. n .. " at (" .. x .. "," .. y .. ")")
        end
      end
    end
    return own / (own + bled), examples
  end

  it("keeps each region DOMINATED by its own tile family, bleeding only harmless ground", function()
    local hot = census(HOT_FAMILY, -195, -72)
    local middle = census(MIDDLE_FAMILY, -52, 52)
    local cold = census(COLD_FAMILY, 72, 195)
    log(string.format("ci-frcw own-family share: hot=%.3f middle=%.3f cold=%.3f", hot, middle, cold))
    -- Measured well above these; the floor is set to catch a scatter that has grown from
    -- flavour into a wash (which would read as one mushy planet, not three regions).
    assert.is_true(hot > 0.85, "the hot slope still reads hot (own-family share " .. hot .. ")")
    assert.is_true(middle > 0.85, "the middle still reads as the ash middle (own-family share " .. middle .. ")")
    assert.is_true(cold > 0.85, "the cold slope still reads cold (own-family share " .. cold .. ")")
  end)

  -- 4a. THE HOT-SIDE FOLDS BRANCH (ci-72bw) ----------------------------------------
  -- The safe hot slope carries TWO texture families over the same value segment, picked by
  -- a low-frequency branch noise: broad regions read folded/pumice, the rest read cracked.
  -- The slope spans perp (72, 130) -> x in (-130, -72).

  it("generates BOTH hot-slope families live: cracked regions AND folded/pumice regions (ci-72bw)", function()
    local folds = count_in(FOLDS, -128, -74, -RY, RY)
    local cracks = count_in(CRACKS, -128, -74, -RY, RY)
    assert.is_true(folds > 500, "the folds/pumice family really paints the hot slope (" .. folds .. " tiles)")
    assert.is_true(cracks > 500, "the cracks family still paints the hot slope (" .. cracks .. " tiles)")
    -- Every folds tile is present, not just the top of the family.
    for name in pairs(FOLDS) do
      assert.is_true(s.count_tiles_filtered({ name = name, area = { { -128, -RY }, { -74, RY } } }) > 0,
        name .. " generates somewhere on the hot slope")
    end
  end)

  it("picks ONE family per REGION (broad folded/cracked patches, not per-tile noise, ci-72bw)", function()
    -- Classify each sampled row by the family that dominates it. A low-frequency selector
    -- gives whole regions to one family; per-tile salt-and-pepper would give ~every row a
    -- 50/50 split and no clear winner.
    local folds_rows, cracks_rows = {}, {}
    for y = -150, 150, 5 do
      local f, c = 0, 0
      for x = -128, -74 do
        local n = tile(x, y)
        if FOLDS[n] then f = f + 1 elseif CRACKS[n] then c = c + 1 end
      end
      if f > c * 2 then folds_rows[#folds_rows + 1] = y
      elseif c > f * 2 then cracks_rows[#cracks_rows + 1] = y end
    end
    assert.is_true(#folds_rows > 0, "some regions of the hot slope read FOLDED (" .. #folds_rows .. " rows)")
    assert.is_true(#cracks_rows > 0, "some regions of the hot slope read CRACKED (" .. #cracks_rows .. " rows)")
  end)

  it("CONVERGES both families on ash-dark at the middle edge (ci-72bw)", function()
    -- Whichever family a region uses, its coldest member thins into ash-dark at the same
    -- value -- the two branches rejoin, so the middle never sees a family boundary.
    --
    -- A region is classified from the slope segment DIRECTLY OUTWARD of the measured band
    -- (perp 76..88, well under half a branch wavelength away) rather than from the whole
    -- slope: the branch noise turns over across the slope's own width, so a row that reads
    -- folded out near the crust can be a cracked region by the time it reaches the
    -- convergence, and grading the convergence by the far end measures that drift instead
    -- of the branch. It also samples the full generated length rather than 300 tiles of
    -- it, because the ci-frcw scatter paints in blobs and a short sample grades the blobs.
    --
    -- The band sits OUTWARD of the folds gate line (perp 64), so both families are equally
    -- free to paint it: the main line MAY bleed inward past that line (the ci-frcw
    -- scatter, the established look), the contained branch may not, and grading them where
    -- only one is allowed would compare the containment rule, not the convergence.
    local BAND_LO, BAND_HI = -74, -66
    local function local_family(y)
      local f, c = 0, 0
      for x = -88, -76 do
        local n = tile(x, y)
        if FOLDS[n] then f = f + 1 elseif CRACKS[n] then c = c + 1 end
      end
      if f > c then return "folds" elseif c > f then return "cracks" end
      return nil
    end
    local stat = {
      folds = { ash = 0, total = 0, hist = {} },
      cracks = { ash = 0, total = 0, hist = {} },
    }
    for y = -RY, RY, 3 do
      local fam = local_family(y)
      if fam then
        for x = BAND_LO, BAND_HI do
          local n = tile(x, y)
          local st = stat[fam]
          st.total = st.total + 1
          st.hist[n] = (st.hist[n] or 0) + 1
          if n == "cindra-volcanic-ash-dark" then st.ash = st.ash + 1 end
        end
      end
    end
    assert.is_true(stat.folds.total > 500 and stat.cracks.total > 500,
      "sampled a meaningful amount of both kinds of region (folds=" .. stat.folds.total ..
      ", cracks=" .. stat.cracks.total .. ")")
    local f_ash = stat.folds.ash / stat.folds.total
    local c_ash = stat.cracks.ash / stat.cracks.total
    log(string.format("ci-72bw convergence ash-dark share: folds=%.3f cracks=%.3f", f_ash, c_ash))
    -- Whichever family the region is, ash-dark is the ground the band is MADE of: the most
    -- common tile in it by a wide margin, and the majority of it.
    for fam, st in pairs(stat) do
      local top, top_n = nil, 0
      for n, c in pairs(st.hist) do
        if c > top_n then top, top_n = n, c end
      end
      assert.are.equal("cindra-volcanic-ash-dark", top,
        fam .. " regions must converge on ash-dark; the band's most common tile is " .. tostring(top))
    end
    -- The absolute floor is lower than ci-72bw shipped it, and deliberately so: the ci-frcw
    -- cosmetic scatter interleaves the slope's own ground into this band (and the ash back
    -- out into the slope) precisely so the transition stops reading as a line. Measured at
    -- ~0.52 / ~0.57; the floor catches a scatter that has grown until the convergence is
    -- no longer recognisably ash.
    assert.is_true(f_ash > 0.4, "folded regions converge on ash-dark (" .. f_ash .. ")")
    assert.is_true(c_ash > 0.4, "cracked regions converge on ash-dark (" .. c_ash .. ")")
    -- And they converge EQUALLY WELL: the branch does not push its own family further in
    -- (or stop it short) relative to the main line it branched from. This is the assertion
    -- ci-72bw exists for, and it keeps its original tightness.
    assert.is_true(math.abs(f_ash - c_ash) < 0.15,
      "both families reach ash-dark alike (folds=" .. f_ash .. ", cracks=" .. c_ash .. ")")
  end)

  it("never leaks folds tiles into the middle or the cold side (ci-72bw)", function()
    -- The branch lives strictly inside the hot slope's value segment, so no folds tile may
    -- appear from the middle band (x >= -60) rightward, all the way to the ice ocean.
    local leaked = count_in(FOLDS, -60, 396, -RY, RY)
    assert.are.equal(0, leaked, "folds-family tiles must never paint the middle/cold side (" .. leaked .. " found)")
    -- Nor above the branch: the lethal hot crust + the lava ocean stay the main line, so
    -- the branch adds no new zero-damage tile out in the heat belt.
    local hot_leak = count_in(FOLDS, -396, -135, -RY, RY)
    assert.are.equal(0, hot_leak, "folds-family tiles must never paint the lethal hot belt (" .. hot_leak .. " found)")
    -- Belt and braces: the whole scanned belt really is lethal ground.
    assert.are.equal("heat", terrain.lethal_at(135), "the scanned hot belt is heat-lethal")
  end)

  it("registers every folds tile as a real Cindra tile on the hot-slope gradient (ci-72bw)", function()
    -- That the folds ground is as HARMLESS as the cracks ground it alternates with is
    -- proven behaviourally, through the real damage sweep, in tests/test_tile_damage.lua;
    -- this pins the prototype side (registered, walkable, on the hot->cold colour ramp).
    for name in pairs(FOLDS) do
      assert.is_not_nil(prototypes.tile[name], name .. " is a real registered Cindra tile")
      assert.is_true(terrain.is_walkable(name), name .. " must be walkable ground")
      assert.is_not_nil(terrain.map_color(name), name .. " sits on the map-view gradient")
    end
  end)

  it("the habitable middle is a MIX of ash tiles (+ soil patches), not one flat tile", function()
    local seen = {}
    for x = -52, 52, 1 do
      for y = -120, 120, 8 do
        local n = tile(x, y)
        if MIDDLE_FAMILY[n] then seen[n] = true end
      end
    end
    local ash = 0
    for _, v in ipairs({ "cindra-volcanic-ash-dark", "cindra-volcanic-ash-light", "cindra-volcanic-ash-flats" }) do
      if seen[v] then ash = ash + 1 end
    end
    assert.is_true(ash >= 2, "the middle mixes at least two ash tiles, saw " .. ash)
    local soil = seen["cindra-volcanic-soil-dark"] or seen["cindra-volcanic-soil-light"] or seen["cindra-volcanic-ash-soil"]
    assert.is_true(soil == true, "the middle grows soil patches")
  end)

  -- 4b. THE COSMETIC CROSS-REGION SCATTER (ci-frcw) --------------------------------
  -- The bead's own words: an organic, less-banded look, bought by letting a point
  -- occasionally paint a tile a band or two from its own -- and bought SAFELY, because
  -- the scatter moves only the value the TILE is picked from, never the field the damage
  -- belts and the resource bands are read from.

  it("scatters NEIGHBOUR-REGION tiles across the middle: cool volcanic AND dust (ci-frcw)", function()
    -- Sampled in the middle's INTERIOR (|perp| <= 40), a long way inside the ordinary
    -- boundary wiggle + speckle bleed, so nothing here can be a band edge blurring: the
    -- only thing that can put a non-middle tile at these coordinates is the scatter.
    -- (Before ci-frcw this area was pure ash + soil, so the count below was zero.)
    local native = terrain.zone_tiles("middle")
    local seen, total, bled = {}, 0, 0
    for x = -40, 40 do
      for y = -200, 200, 4 do
        local n = tile(x, y)
        total = total + 1
        if not native[n] then bled = bled + 1; seen[n] = (seen[n] or 0) + 1 end
      end
    end
    local names = {}
    for n, c in pairs(seen) do names[#names + 1] = n .. "=" .. c end
    table.sort(names)
    log("ci-frcw middle scatter: " .. bled .. "/" .. total .. " -> " .. table.concat(names, " "))
    assert.is_true(bled > 0, "the middle really wears tiles that are not its own")
    -- Both directions: a patch of the hot side's cool volcanic ground AND a patch of the
    -- cold side's dust turn up out in the habitable band.
    assert.is_true((seen["cindra-volcanic-smooth-stone"] or 0) + (seen["cindra-volcanic-cracks"] or 0) > 0,
      "the middle wears patches of the cool volcanic slope")
    local dust = 0
    for _, v in ipairs({ "dust-flat", "dust-crests", "dust-lumpy", "dust-patchy" }) do
      dust = dust + (seen["cindra-" .. v] or 0)
    end
    assert.is_true(dust > 0, "the middle wears patches of the cold side's dust")
    -- Flavour, not a wash: the ash middle is still overwhelmingly ash.
    assert.is_true(bled / total < 0.25,
      "the scatter stays occasional (" .. string.format("%.3f", bled / total) .. " of the middle)")
    -- And every scattered tile is decoration: harmless, walkable, never an ocean tile.
    for n in pairs(seen) do
      assert.are.equal(0, (terrain.tile_damage(n)), n .. " scattered into the middle must be harmless")
      assert.is_true(terrain.is_walkable(n) == true, n .. " scattered into the middle must be walkable")
      assert.is_true(LAVA[n] ~= true and n ~= "cindra-ice-smooth",
        n .. " must never scatter into the middle (it is an ocean tile)")
    end
  end)

  it("leaks NO damaging ground anywhere the scatter can reach (ci-frcw)", function()
    -- THE hard guard the scatter has to earn: not one tile that burns or freezes exists
    -- in the corridor. Counted over the whole sampled band, every damaging tile named by
    -- the value ramp -- not sampled points, so a single leaked hot crack fails. (An
    -- unwindowed scatter really does leak them: it put glowing cracks-hot in the middle,
    -- which is what the ci-w87 glowing-rock and ci-i4z safe-band guards caught.)
    --
    -- The box is proven to COVER the scatter: the scatter is windowed shut outside the
    -- value range below, whose two contours are asserted to lie inside it. So this is not
    -- "no leak at the places we looked" -- it is "no leak anywhere a leak was possible".
    -- Further out, where the box ends, the ground is bit-identical to a world generated
    -- without this bead (the window is shut there), so the ci-4iw resource keep-back and
    -- its own guards still cover the rest.
    -- The window's two contours, in world tiles (perp = -x on this orientation), rounded
    -- OUTWARD so the box is a strict superset of the scatter-active band.
    local scatter_hot = terrain.field_crossing(terrain.HOT_DMG - terrain.SCATTER_GUARD_HOT)
    local scatter_cold = terrain.field_crossing(terrain.COLD_DMG + terrain.SCATTER_GUARD_COLD)
    assert.is_true(scatter_hot > 0 and scatter_cold < 0,
      "the scatter acts across the middle (perp " .. scatter_cold .. " .. " .. scatter_hot .. ")")
    local box = { { -math.ceil(scatter_hot), -RY }, { -math.floor(scatter_cold), RY } }
    log(string.format("ci-frcw scatter-active band: perp %.1f .. %.1f (x %d .. %d)",
      scatter_cold, scatter_hot, box[1][1], box[2][1]))
    for _, kind in ipairs({ "heat", "cold" }) do
      for _, name in ipairs(terrain.tiles_by_damage(kind)) do
        assert.are.equal(0, s.count_tiles_filtered({ name = name, area = box }),
          "no " .. kind .. "-damaging ground (" .. name .. ") may exist in the safe corridor")
      end
    end
    -- Not vacuous: those same tiles really do generate out in their own belts.
    local belts = 0
    for _, kind in ipairs({ "heat", "cold" }) do
      for _, name in ipairs(terrain.tiles_by_damage(kind)) do
        belts = belts + s.count_tiles_filtered({ name = name, area = { { -396, -RY }, { 396, RY } } })
      end
    end
    assert.is_true(belts > 1000, "damaging ground really does exist on this map (" .. belts .. " tiles)")
  end)

  it("draws ORGANIC (wavy) region boundaries, never raw straight lines", function()
    local first = {}
    for y = -160, 160, 10 do
      for x = 40, 120 do
        if COLD_FAMILY[tile(x, y)] and not MIDDLE_FAMILY[tile(x, y)] then first[#first + 1] = x; break end
      end
    end
    assert.is_true(#first >= 8, "sampled enough rows to judge the boundary")
    local lo, hi = first[1], first[1]
    for _, x in ipairs(first) do lo = math.min(lo, x); hi = math.max(hi, x) end
    assert.is_true(hi - lo >= 3, "the boundary wanders across rows (organic); spread=" .. tostring(hi - lo))
  end)

  -- 5. WALKABILITY -----------------------------------------------------------------
  it("makes ONLY the lava tiles impassable; smooth-ice is now walkable (ci-wly)", function()
    local function pave(name, cx, cy)
      local t = {}
      for x = cx - 4, cx + 4 do for y = cy - 4, cy + 4 do t[#t + 1] = { name = name, position = { x, y } } end end
      s.set_tiles(t, true)
    end
    local WY = 2600
    local function buildable(name)
      pave(name, 0, WY)
      return s.can_place_entity({ name = "stone-furnace", position = { 0, WY } })
    end
    assert.is_false(buildable("cindra-lava-hot"), "hot lava is impassable (unbuildable)")
    assert.is_false(buildable("cindra-lava"), "lava is impassable (unbuildable)")
    assert.is_true(buildable("cindra-ice-smooth"), "smooth-ice is now WALKABLE/buildable (you can run on it)")
    for _, walk in ipairs({ "cindra-volcanic-cracks-hot", "cindra-volcanic-ash-flats",
                            "cindra-dust-flat", "cindra-ice-rough", "cindra-snow-flat",
                            -- the ci-72bw folds branch is ordinary buildable slope ground
                            "cindra-volcanic-folds-warm", "cindra-volcanic-folds",
                            "cindra-volcanic-folds-flat", "cindra-volcanic-ash-cracks",
                            "cindra-volcanic-pumice-stones" }) do
      assert.is_true(buildable(walk), walk .. " is buildable ground")
    end
  end)

  -- 6. DAMAGE (positional descriptor) ----------------------------------------------
  it("flags the damage zones: hot ocean+inner (heat), cold inner+ocean (cold), middle safe", function()
    assert.are.equal("heat", terrain.lethal_at(-(-300)), "the hot-lava ocean is heat-lethal")
    assert.are.equal("heat", terrain.lethal_at(-(-150)), "the hot inner slope is heat-lethal")
    assert.are.equal("cold", terrain.lethal_at(-(150)), "the cold inner slope is cold-lethal")
    assert.are.equal("cold", terrain.lethal_at(-(300)), "the ice ocean is cold-lethal")
    assert.is_nil(terrain.lethal_at(-(0)), "the middle centre is safe")
    assert.is_nil(terrain.lethal_at(-(-90)), "the hot outer slope is safe")
    assert.is_nil(terrain.lethal_at(-(90)), "the cold outer slope is safe")
  end)

  -- 7. ZERO NAUVIS LEAKAGE ---------------------------------------------------------
  it("generates NO un-cloned grass and NO water anywhere (no nauvis terrain leakage)", function()
    local box = { { -396, -RY }, { 396, RY } }
    for _, n in ipairs({ "grass-1", "grass-2", "grass-3", "grass-4", "water", "deepwater" }) do
      assert.are.equal(0, s.count_tiles_filtered({ name = n, area = box }), "Cindra must generate no un-cloned " .. n)
    end
  end)

  it("paints ONLY Cindra tiles across the interior (every point is a cindra-* tile)", function()
    local cindra_set = {}
    for _, n in ipairs(terrain.tile_names()) do cindra_set[n] = true end
    for x = -390, 390, 40 do
      for y = -120, 120, 60 do
        local n = tile(x, y)
        assert.is_true(cindra_set[n] == true, "interior tile at (" .. x .. "," .. y .. ") must be a Cindra tile, got " .. n)
      end
    end
  end)

  -- 8. NATIVE RESOURCES, banded --------------------------------------------------
  local function count(name, x1, x2)
    return s.count_entities_filtered({ name = name, area = { { x1, -RY }, { x2, RY } } })
  end

  it("places stone on the middle + survivable hot margin, never on the cold side", function()
    -- stone zone perp [-60, 120.5) -> x in (-120.5, 60].
    assert.is_true(count(field.STONE, -118, 60) > 0, "stone patches on the hot ribbon")
    assert.are.equal(0, count(field.STONE, 65, 400), "no stone on the cold side (east)")
  end)

  it("places ice on the survivable cold margin, never on the hot/temperate ribbon", function()
    -- ice zone perp (-120.5, -60) -> patch CENTRES at x in (60, 120.5). Resource spots
    -- are sparse blobs, so assert on entity centres over a generous band (robust to which
    -- x a given seed's spot lands at) rather than a tight bounding-box count.
    local ice = s.find_entities_filtered({ name = field.ICE, area = { { 55, -RY }, { 130, RY } } })
    local in_band = 0
    for _, e in ipairs(ice) do if e.position.x > 60 then in_band = in_band + 1 end end
    assert.is_true(in_band > 0, "ice patches on the survivable cold margin (found " .. in_band .. ")")
    -- Purity: no ice patch CENTRED on the hot/temperate side (x <= 60), the divider.
    local warm = s.find_entities_filtered({ name = field.ICE, area = { { -400, -RY }, { 60, RY } } })
    local warm_leak = 0
    for _, e in ipairs(warm) do if e.position.x < 60 then warm_leak = warm_leak + 1 end end
    assert.are.equal(0, warm_leak, "no ice centred on the hot/temperate ribbon (found " .. warm_leak .. ")")
  end)

  it("keeps ALL harvestable fields OUT of both damage zones (ci-fb9)", function()
    -- heat zone perp >= 130 -> x <= -130; cold zone perp <= -130 -> x >= 130.
    assert.are.equal(0, count(field.STONE, -400, -131), "no stone in the heat damage zone")
    assert.are.equal(0, count(field.ICE, -400, -131), "no ice in the heat damage zone")
    assert.are.equal(0, count(field.STONE, 131, 400), "no stone in the cold damage zone")
    assert.are.equal(0, count(field.ICE, 131, 400), "no ice in the cold damage zone")
    assert.are.equal("heat", terrain.lethal_at(-(-150)), "the west scanned band really is heat-lethal")
    assert.are.equal("cold", terrain.lethal_at(-(150)), "the east scanned band really is cold-lethal")
  end)

  it("no stone/ice field ever sits on a lethal death tile (ci-4iw)", function()
    local DEATH = {
      ["cindra-ice-smooth"] = true, ["cindra-lava-hot"] = true, ["cindra-lava"] = true,
      ["cindra-volcanic-smooth-stone-warm"] = true, ["cindra-volcanic-cracks-hot"] = true,
      ["cindra-ice-rough"] = true,
    }
    local function scan(name)
      local ents = s.find_entities_filtered({ name = name, area = { { -400, -RY }, { 400, RY } } })
      local on_death = 0
      for _, e in ipairs(ents) do
        local p = e.position
        if DEATH[s.get_tile(p.x, p.y).name] then on_death = on_death + 1 end
      end
      return #ents, on_death
    end
    local n_stone, bad_stone = scan(field.STONE)
    local n_ice, bad_ice = scan(field.ICE)
    assert.is_true(n_stone > 0, "sampled real stone fields")
    assert.is_true(n_ice > 0, "sampled real ice fields")
    assert.are.equal(0, bad_stone, "no stone field on a death tile (" .. bad_stone .. " found)")
    assert.are.equal(0, bad_ice, "no ice field on a death tile (" .. bad_ice .. " found)")
  end)

  -- 8a. BOOTSTRAP + BURNED ROCKS ---------------------------------------------------
  it("scatters bootstrap rocks across the warm middle, fading before ice (ci-18n)", function()
    -- sandy rock band perp [-55, 60] -> x in [-60, 55].
    assert.is_true(s.count_entities_filtered({ name = field.ROCK, area = { { -59, -100 }, { 54, 100 } } }) > 0,
      "bootstrap rocks scatter across the warm middle")
    assert.are.equal(0, s.count_entities_filtered({ name = field.ROCK, area = { { -195, -100 }, { -70, 100 } } }),
      "no rocks out in the hot margin (masked to the middle)")
    assert.are.equal(0, s.count_entities_filtered({ name = field.ROCK, area = { { 62, -RY }, { 120, RY } } }),
      "no sandy rocks on the frosty cold edge (fades before ice, ci-18n)")
  end)

  -- Every ice-rock SIZE is counted, not just the big one (ci-w87): the cold rocks are
  -- an iceberg family now, and a guard that watched one member would go quiet the
  -- moment placement regressed on the other.
  local function count_ice_rocks(x1, x2)
    local n = 0
    for _, name in ipairs(field.ice_rock_names()) do
      n = n + s.count_entities_filtered({ name = name, area = { { x1, -RY }, { x2, RY } } })
    end
    return n
  end

  it("scatters ice-rocks across the safe cold band, never the lethal cold zone (ci-18n)", function()
    -- ice-rock band perp (-130, -60] -> x in [60, 130).
    assert.is_true(count_ice_rocks(62, 128) > 0, "ice-rocks scatter across the safe cold band")
    assert.are.equal(0, count_ice_rocks(132, 400), "no ice-rocks in the lethal cold damage zone")
    local warm_leak = 0
    for _, name in ipairs(field.ice_rock_names()) do
      for _, e in ipairs(s.find_entities_filtered({ name = name, area = { { -400, -RY }, { 65, RY } } })) do
        if e.position.x < 59 then warm_leak = warm_leak + 1 end
      end
    end
    assert.are.equal(0, warm_leak, "no ice-rocks centred on the warm/temperate ribbon")
  end)

  -- ci-w87: the cold side used to be one boulder model recoloured blue. It is the
  -- lithium ice-formation family now, and BOTH entity sizes have to actually turn up --
  -- a size that never generates is art the player never sees.
  it("generates BOTH ice-formation sizes on the cold ground (ci-w87)", function()
    for _, name in ipairs(field.ice_rock_names()) do
      assert.is_true(s.count_entities_filtered({ name = name, area = { { 62, -RY }, { 128, RY } } }) > 0,
        name .. " must generate in the safe cold band")
    end
  end)

  -- ci-tizx: the ice-rock chunks share the cold outer band with the frost decals, and
  -- at the original 0.006 the two together buried the ground tiles. The scatter must
  -- stay THIN enough that the terrain reads through it, while still bootstrapping.
  it("keeps the ice-rock scatter thin enough to see the ground through (ci-tizx)", function()
    local x1, x2, y1, y2 = 62, 128, -300, 300
    -- The WHOLE family (ci-w87): splitting one scatter across two iceberg sizes must
    -- not sneak extra rocks past this ceiling, so the total is what is measured.
    local n = 0
    for _, name in ipairs(field.ice_rock_names()) do
      n = n + s.count_entities_filtered({ name = name, area = { { x1, y1 }, { x2, y2 } } })
    end
    local per_tile = n / ((x2 - x1) * (y2 - y1))
    log("ci-tizx ice-rock density: " .. n .. " -> " .. per_tile .. " per tile")
    assert.is_true(per_tile > 0.0002, "still an ample hand-mined bootstrap scatter")
    -- Measured: ~0.0029/tile at the ci-tizx density, ~0.0058 at the original one --
    -- the ceiling sits between the two, so a regression to the carpet fails here.
    assert.is_true(per_tile < 0.0042,
      "ice-rocks stay sparse (" .. string.format("%.5f", per_tile) .. " per tile)")
  end)

  local function count_burned(x1, x2)
    local n = 0
    for _, name in ipairs(field.burned_rock_names()) do
      n = n + s.count_entities_filtered({ name = name, area = { { x1, -RY }, { x2, RY } } })
    end
    return n
  end

  it("generates burned volcanic rocks in the hot region, clustered toward the lava (ci-qy0)", function()
    -- volcanic band perp (60,200] -> x in [-200,-60).
    assert.is_true(count_burned(-195, -65) > 0, "burned rocks generate in the hot region")
    local near_lava = count_burned(-195, -135)
    local inner = count_burned(-90, -65)
    assert.is_true(near_lava >= inner, "burned rocks cluster toward the lava (near=" .. near_lava .. ", inner=" .. inner .. ")")
  end)

  it("keeps burned rocks OUT of the middle and the cold side (ci-qy0)", function()
    assert.are.equal(0, count_burned(-55, 55), "no burned rocks in the middle")
    assert.are.equal(0, count_burned(65, 400), "no burned rocks in the cold/ice side")
  end)

  -- ci-w87: which volcanic MODEL you see is a truthful read of the ground. The glowing
  -- (`-hot`) boulders belong inside the lava area; the plain charred ones belong on the
  -- safe hot slope. Both halves are asserted from the LIVE surface: where the rocks
  -- actually landed, and what the tile under each one actually does to the player.
  local function volcanic_rocks()
    local out = {}
    for _, name in ipairs(field.burned_rock_names()) do
      for _, e in ipairs(s.find_entities_filtered({ name = name, area = { { -400, -RY }, { 400, RY } } })) do
        out[#out + 1] = e
      end
    end
    return out
  end

  -- THE invariant this bead exists for, stated as what the player experiences: a rock
  -- that GLOWS is standing on ground that burns, and a rock that does not is standing
  -- on ground that does not. Checked on EVERY generated rock -- no sampling, no margin
  -- around the band edge, because the model is gated on the tile itself and so cannot
  -- disagree with it anywhere.
  it("a GLOWING rock means the ground under it burns, a plain one means it does not (ci-w87)", function()
    local rocks = volcanic_rocks()
    assert.is_true(#rocks > 0, "volcanic rocks generate at all")
    local hot_seen, cool_seen, wrong = 0, 0, {}
    for _, e in ipairs(rocks) do
      local intensity, kind = terrain.tile_damage(s.get_tile(e.position.x, e.position.y).name)
      local ground_burns = intensity > 0 and kind == "heat"
      local glows = field.is_hot_burned_rock(e.name)
      if glows then hot_seen = hot_seen + 1 else cool_seen = cool_seen + 1 end
      if glows ~= ground_burns and #wrong < 5 then
        wrong[#wrong + 1] = e.name .. " at " .. string.format("%.1f,%.1f", e.position.x, e.position.y)
          .. " on " .. s.get_tile(e.position.x, e.position.y).name
      end
    end
    assert.are.equal(0, #wrong,
      "rocks whose model lies about the ground they stand on: " .. table.concat(wrong, ", "))
    assert.is_true(hot_seen > 0, "glowing rocks actually generate on burning ground")
    assert.is_true(cool_seen > 0, "plain rocks actually generate on safe ground")
  end)

  it("keeps the glowing rocks in the LAVA AREA, never the habitable band (ci-w87)", function()
    -- The burning ground only exists in the hot region, so gating on the tile also
    -- keeps the glowing boulders out of the band the player builds in.
    local strays = 0
    for _, e in ipairs(volcanic_rocks()) do
      if field.is_hot_burned_rock(e.name) and -e.position.x < field.lava_edge() - 20 then
        strays = strays + 1
      end
    end
    assert.are.equal(0, strays, "glowing rocks well warmward of the lava area")
  end)

  it("generates every volcanic size in BOTH the plain and the glowing model (ci-w87)", function()
    for _, name in ipairs(field.burned_rock_names()) do
      assert.is_true(s.count_entities_filtered({ name = name, area = { { -400, -RY }, { 400, RY } } }) > 0,
        name .. " must actually generate somewhere on the hot side")
    end
  end)

  it("coal is reachable SAFELY: volcanic rocks generate in the non-lethal hot margin (ci-18n)", function()
    -- safe hot margin perp (60,130) -> x in (-130,-60]; heat damage perp >= 130 (x <= -130).
    assert.is_true(count_burned(-128, -65) > 0, "volcanic rocks (coal) generate in the SAFE hot margin")
    assert.is_nil(terrain.lethal_at(-(-65)), "the inner edge of the sampled band is safe")
    assert.is_nil(terrain.lethal_at(-(-128)), "the outer edge of the sampled band is still safe")
  end)

  -- 9. NO CLIFFS -------------------------------------------------------------------
  it("generates NO cliffs: the ribbon stays flat and traversable (ci-qqt)", function()
    assert.are.equal(0, s.count_entities_filtered({ type = "cliff", area = { { -400, -RY }, { 400, RY } } }),
      "the ribbon is cliff-free")
  end)

  -- LANDABILITY --------------------------------------------------------------------
  it("LANDABLE: the spawn tile + a base-sized pad are walkable, safe cindra ground", function()
    for x = -8, 8 do
      for y = -8, 8 do
        local n = tile(x, y)
        assert.matches("^cindra%-", n, "landing pad tile (" .. x .. "," .. y .. ") must be a cindra tile, got: " .. n)
        assert.is_true(terrain.is_walkable(n), "landing pad tile (" .. x .. "," .. y .. ") must be walkable, got: " .. n)
        -- Damage is positional now (ci-oe83): the spawn pad is in the safe middle band.
        assert.is_nil(terrain.lethal_at(-x), "landing pad column x=" .. x .. " must be damage-free (safe middle)")
      end
    end
  end)

  it("LANDABLE: a character dropped at spawn takes zero damage from a live tile-damage sweep", function()
    local char = s.create_entity({ name = "character", position = { 0, 0 }, force = "player" })
    assert.is_not_nil(char, "a character must be placeable at spawn")
    local before = char.health
    tile_damage.sweep(s, tile_damage.DAMAGE_INTERVAL, 200)
    assert.are.equal(before, char.health, "a character at the landing spot must take ZERO environmental damage")
    char.destroy()
  end)

  -- FINITE SURFACE + SLIDERS + MAP COLOUR -----------------------------------------
  it("bounds the REAL cindra planet surface at creation (the runtime hook works)", function()
    local live = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local mg = live.map_gen_settings
    assert.are.equal(800, mg.width, "the cindra surface is finite (800) on the perpendicular (X) axis")
    assert.is_true(mg.height == 0 or mg.height > 100000,
      "the ribbon is infinite along its long (Y) axis; got height=" .. tostring(mg.height))
  end)

  it("exposes real map-gen sliders: Stone + Ice are the only RESOURCE sliders", function()
    for _, n in ipairs({ "cindra-stone", "cindra-ice" }) do
      local ctrl = prototypes.autoplace_control[n]
      assert.is_not_nil(ctrl, n .. " autoplace-control exists")
      assert.are.equal("resource", ctrl.category, n .. " is a resource slider")
    end
    -- There is no standalone ice-derived ore (ci-3yl), so Cindra's map-gen screen must
    -- never grow a third RESOURCE slider. (It does carry terrain-category sliders for
    -- the ribbon geometry -- ci-i4z, tests/test_worldgen_sliders.lua.)
    local base = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local resource_sliders = {}
    for name in pairs(base.map_gen_settings.autoplace_controls) do
      local ctrl = prototypes.autoplace_control[name]
      if ctrl and ctrl.category == "resource" then resource_sliders[#resource_sliders + 1] = name end
    end
    table.sort(resource_sliders)
    assert.are.same({ "cindra-ice", "cindra-stone" }, resource_sliders,
      "exactly two resource sliders; got " .. table.concat(resource_sliders, ", "))
  end)

  it("marks the danger zones on the map: hot + cold edges carry a distinct map_color (ci-4h7)", function()
    local function mc(name)
      local c = prototypes.tile[name].map_color
      assert.is_not_nil(c, name .. " has a map_color")
      local scale = (c.r > 1 or c.g > 1 or c.b > 1) and 255 or 1
      return { c.r / scale, c.g / scale, c.b / scale }
    end
    local function dist(a, b) return math.abs(a[1]-b[1]) + math.abs(a[2]-b[2]) + math.abs(a[3]-b[3]) end
    local center = mc("cindra-volcanic-ash-flats")
    local lava, ice = mc("cindra-lava-hot"), mc("cindra-ice-smooth")
    assert.is_true(dist(lava, center) > 0.5, "the hot-lava danger edge is distinct from the middle")
    assert.is_true(dist(ice, center) > 0.4, "the deep-ice danger edge is distinct from the middle")
    assert.is_true(lava[1] > lava[2] and lava[1] > lava[3], "hot lava reads red/orange on the map")
    assert.is_true(ice[3] > ice[1], "deep ice reads cold (blue) on the map")
    local vlava = prototypes.tile["lava"]
    if vlava and vlava.map_color then
      local vs = (vlava.map_color.r > 1 or vlava.map_color.g > 1 or vlava.map_color.b > 1) and 255 or 1
      assert.is_true(dist(lava, { vlava.map_color.r / vs, vlava.map_color.g / vs, vlava.map_color.b / vs }) > 0.05,
        "Cindra hot-lava has its own map_color; vanilla lava is untouched")
    end
  end)
end)
