-- Guard: Cindra stays a well-behaved PlanetsLib CITIZEN without depending on it.
--
-- ci-810e evaluated PlanetsLib 1.23.5 (commit ba3dd7a) and recommended NOT taking
-- a dependency on it -- see docs/planetslib-evaluation.md for the full read. But
-- players DO install it alongside planet mods, and its `data-final-fixes` imposes
-- hard preconditions on every planet in `data.raw.planet`, Cindra included. Two of
-- those preconditions can be violated by an innocent-looking edit to
-- prototypes/planet.lua, and neither would ever be caught by our own suite,
-- because our suite does not (and should not) ship PlanetsLib.
--
-- So: pin the preconditions here, from OUR side of the fence. Every assertion
-- below reads only Cindra's own prototype. Nothing here requires PlanetsLib to be
-- installed, nothing here adds a dependency, and nothing here constrains any
-- other planet.
--
-- Sibling coverage: tests/test_planet.lua already pins the tuned star-map
-- position itself (distance 5, sunward of Vulcanus, the tidal-lock quarter turn).
-- This file guards the LIBRARY-INTEROP edges that file does not.

local H = require("tests.helpers")

-- PlanetsLib's `lib/planet-str.lua` encodes an 8-byte planet string. When a planet
-- does not set one, `data-final-fixes` autogenerates it as `string.sub(name, 1, 8)`.
local PLANET_STR_MAX = 8

-- `lib/orbits.lua :: SPECIAL_PLACEHOLDERS_FOR_MISSING_PARENT`. When `PlanetsLib:extend`
-- is handed an `orbit.parent` that is not loaded, it does NOT error -- it silently
-- parks the planet at these coordinates, i.e. flung off the edge of the star map.
local MISSING_PARENT_DISTANCE = 43168
local MISSING_PARENT_ORIENTATION = 0.43168

-- `data-final-fixes.lua` asserts these sum to <= 100 across a planet's
-- surface_properties (unless `PlanetsLib-enforce-gas-percentage` is forced off).
-- They are defined BY PlanetsLib, not by vanilla, so they only exist when it is
-- installed.
local GAS_PROPERTIES = { "oxygen", "nitrogen", "carbon-dioxide", "argon" }

-- Read a surface property that may not be defined in this mod set. Returns nil
-- when the property does not exist (the vanilla 4-mod run), rather than erroring.
local function optional_property(surface, name)
  local ok, value = pcall(function() return surface.get_property(name) end)
  if ok then return value end
  return nil
end

describe("PlanetsLib interop", function()
  it("has a planet name that survives the 8-byte planet-str encoding", function()
    local cindra = game.planets["cindra"]
    assert.is_not_nil(cindra, "cindra planet must exist")
    assert.is_true(#cindra.name <= PLANET_STR_MAX,
      "PlanetsLib encodes an autogenerated planet-str as name:sub(1,8); a longer"
      .. " Cindra name would be silently truncated. Got " .. #cindra.name
      .. " chars: " .. cindra.name)
  end)

  it("does not collide with another loaded planet in its first 8 characters", function()
    -- Two planets whose names share a 1..8 prefix get the SAME autogenerated
    -- planet-str, so any PlanetsLib feature keyed on it would confuse them. Only
    -- Cindra's prefix is our business, so that is all this asserts.
    local prefix = string.sub("cindra", 1, PLANET_STR_MAX)
    for name in pairs(game.planets) do
      if name ~= "cindra" then
        assert.are_not.equal(prefix, string.sub(name, 1, PLANET_STR_MAX),
          "planet '" .. name .. "' shares Cindra's 8-character planet-str prefix")
      end
    end
  end)

  it("is not parked on PlanetsLib's missing-parent placeholder position", function()
    -- A future migration onto `PlanetsLib:extend{ orbit = { parent = ... } }` that
    -- named an absent parent would land the planet HERE instead of failing loudly.
    -- Cindra orbits the star directly, so this must never be its position.
    local loc = prototypes.space_location["cindra"]
    assert.is_not_nil(loc, "cindra space location must exist")
    assert.is_true(math.abs(loc.distance - MISSING_PARENT_DISTANCE) > 1e-6,
      "cindra is sitting on PlanetsLib's missing-parent placeholder distance ("
      .. MISSING_PARENT_DISTANCE .. "): its orbit parent did not resolve")
    assert.is_true(math.abs(loc.orientation - MISSING_PARENT_ORIENTATION) > 1e-6,
      "cindra is sitting on PlanetsLib's missing-parent placeholder orientation ("
      .. MISSING_PARENT_ORIENTATION .. "): its orbit parent did not resolve")
  end)

  it("has a well-formed polar position, so a star-parented orbit is the identity", function()
    -- PlanetsLib's `get_absolute_polar_position_from_orbit` short-circuits on
    -- `parent.name == "star"` and returns `orbit.distance, orbit.orientation`
    -- unchanged, and `ensure_all_locations_have_orbits` retro-fits exactly that
    -- orbit onto any planet lacking one. So adopting PlanetsLib CANNOT move Cindra
    -- -- provided its position is a well-formed polar coordinate to begin with.
    local loc = prototypes.space_location["cindra"]
    assert.is_true(loc.distance > 0,
      "cindra must sit off the star at a positive orbital distance; got "
      .. tostring(loc.distance))
    assert.is_true(loc.orientation >= 0 and loc.orientation < 1,
      "orientation is a RealOrientation in [0, 1); got " .. tostring(loc.orientation))
  end)

  it("declares an atmosphere that cannot trip the gas-percentage assert", function()
    -- The live trap. PlanetsLib hard-asserts in data-final-fixes that a planet's
    -- oxygen + nitrogen + carbon-dioxide + argon sum to <= 100, and a failed assert
    -- REFUSES TO LOAD THE GAME. Cindra declares no gas properties today ("the air
    -- itself would boil, were there any"), so the sum is 0. If a future
    -- atmosphere pass adds them, this keeps the total legal.
    --
    -- These properties only exist when PlanetsLib is installed, so on the plain
    -- 4-mod run this reads them as absent and the sum stays 0 -- the assertion is
    -- still meaningful the moment someone adds a `surface_properties.oxygen`.
    local s = H.cindra_surface()
    local total = 0
    for _, gas in ipairs(GAS_PROPERTIES) do
      local value = optional_property(s, gas)
      if value then total = total + value end
    end
    assert.is_true(total <= 100,
      "cindra's combined gas surface properties must stay <= 100 or PlanetsLib's"
      .. " data-final-fixes assert refuses to load the game; got " .. tostring(total))
  end)
end)
