-- Proof: Cindra is a REAL ribbon planet generated by the MAP-GEN itself, a THREE-PART
-- TWO-HEIGHTMAP world (ci-3yl worldgen; ci-wly rebuild).
--
-- No on_chunk_generated script paints or voids anything. This drives the actual planet
-- map_gen_settings on a fresh, fixed-seed surface and proves, on the default vertical
-- orientation (ribbon long axis = Y; hot-cold gradient = X, hot on the LEFT / west,
-- perp = -x):
--   1. FINITE PERPENDICULAR: width = SUM of the zone widths (800) voids beyond the band.
--   2. TWO INTEGRATED OCEANS: the sunward hot-lava ocean AND the nightward smooth-ice
--      ocean each generate as a SOLID contiguous sea at the map edge, seed-independent,
--      FOLDED INTO the heightmap (never stamped on top).
--   3. HEIGHTMAP RINGS: lava/ice sit in pools ringed by their crust; each ocean thins
--      toward the habitable middle.
--   4. THREE REGIONS: the hot slope is hot-family tiles, the middle is the ash mix +
--      soil, the cold slope is cold-family tiles; the families never cross the middle.
--   5. WALKABILITY: only the two lava tiles are impassable; smooth-ice is now WALKABLE.
--   6. DAMAGE: positional -- the hot ocean+inner burn, the cold inner+ocean freeze.
--   7. ZERO NAUVIS LEAKAGE. 8. NATIVE RESOURCES banded. 9. NO CLIFFS. 10. LANDABLE.
--
-- The pure zone geometry is proven in unit-tests/test_terrain + test_resource_field;
-- this proves it actually generates on a live surface.

local field = require("scripts.resource-field")
local terrain = require("scripts.terrain")
local tile_damage = require("scripts.tile-damage")

describe("cindra worldgen: a three-part two-heightmap ribbon planet (§4; ci-wly)", function()
  local s
  local ready = false
  local RY = 350

  before_each(function()
    if ready then return end
    local base = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local mgs = base.map_gen_settings
    mgs.seed = 2468
    local fd = terrain.finite_dimension()
    mgs[fd.key] = fd.value
    s = game.surfaces["cindra-worldgen-test"] or game.create_surface("cindra-worldgen-test", mgs)
    -- Radius 15 chunks (~480 tiles) covers the full x in [-400,400] out to y ~= +/-RY.
    s.request_to_generate_chunks({ 0, 0 }, 15)
    s.force_generate_chunk_requests()
    ready = true
  end)

  local function tile(x, y) return s.get_tile(x, y).name end

  local HOT_FAMILY, MIDDLE_FAMILY, COLD_FAMILY = {}, {}, {}
  for _, v in ipairs({ "lava-hot", "lava", "volcanic-smooth-stone-warm", "volcanic-cracks-hot",
                       "volcanic-cracks-warm", "volcanic-cracks", "volcanic-smooth-stone", "volcanic-ash-dark" }) do
    HOT_FAMILY["cindra-" .. v] = true
  end
  for _, v in ipairs({ "volcanic-ash-dark", "volcanic-ash-light", "volcanic-ash-flats",
                       "volcanic-ash-soil", "volcanic-soil-light", "volcanic-soil-dark" }) do
    MIDDLE_FAMILY["cindra-" .. v] = true
  end
  for _, v in ipairs({ "ice-smooth", "ice-rough", "snow-patchy", "snow-lumpy", "snow-crests", "snow-flat",
                       "dust-patchy", "dust-lumpy", "dust-crests", "dust-flat", "volcanic-ash-light" }) do
    COLD_FAMILY["cindra-" .. v] = true
  end
  local LAVA = { ["cindra-lava-hot"] = true, ["cindra-lava"] = true }
  local HOT_CRUST = {
    ["cindra-volcanic-cracks-hot"] = true, ["cindra-volcanic-cracks-warm"] = true,
    ["cindra-volcanic-smooth-stone-warm"] = true,
  }
  local COLD_RING = {}
  for _, v in ipairs({ "ice-rough", "snow-patchy", "snow-lumpy", "snow-crests", "snow-flat" }) do
    COLD_RING["cindra-" .. v] = true
  end

  local function count_in(names_set, x1, x2, y1, y2)
    local n = 0
    for _, name in ipairs(terrain.tile_names()) do
      if names_set[name] then n = n + s.count_tiles_filtered({ name = name, area = { { x1, y1 }, { x2, y2 } } }) end
    end
    return n
  end

  -- 1. FINITE PERPENDICULAR --------------------------------------------------------
  it("is finite perpendicular: the map-gen voids beyond the total width (800), interior playable", function()
    assert.are.equal("out-of-map", tile(-410, 0), "sunward (west) beyond the ribbon is void")
    assert.are.equal("out-of-map", tile(410, 0), "nightward (east) beyond the ribbon is void")
    assert.are_not.equal("out-of-map", tile(0, 0), "the middle centre is playable")
    assert.are_not.equal("out-of-map", tile(-390, 0), "the hot-lava ocean edge is still land")
    assert.are_not.equal("out-of-map", tile(390, 0), "the ice ocean edge is still land")
  end)

  -- 2. TWO INTEGRATED, SOLID OCEANS ------------------------------------------------
  it("generates a SOLID hot-lava OCEAN at the sunward edge, zero gaps (ci-wly)", function()
    -- hot ocean band perp [200,400] -> x in [-400,-200]. Scan the interior.
    local box = { { -396, -RY }, { -204, RY } }
    local gaps = 0
    for _, name in ipairs(terrain.tile_names()) do
      if name ~= "cindra-lava-hot" then gaps = gaps + s.count_tiles_filtered({ name = name, area = box }) end
    end
    assert.are.equal(0, gaps, "the hot-lava ocean is a SOLID sea (found " .. gaps .. " non-lava-hot tiles)")
    assert.is_true(s.count_tiles_filtered({ name = "cindra-lava-hot", area = box }) > 1000, "large contiguous lava ocean")
  end)

  it("generates a SOLID smooth-ice OCEAN at the nightward edge -- INTEGRATED, not stamped (ci-wly/ci-7jc)", function()
    -- ice ocean band perp [-400,-200] -> x in [200,400]. The KEYSTONE cold-side fix: the
    -- ice ocean is the elevation PEAK of the cold heightmap, NOT a rectangle stamped over
    -- a finished map -- so it has no gaps and rings radiate inward from it.
    local box = { { 204, -RY }, { 396, RY } }
    local gaps = 0
    for _, name in ipairs(terrain.tile_names()) do
      if name ~= "cindra-ice-smooth" then gaps = gaps + s.count_tiles_filtered({ name = name, area = box }) end
    end
    assert.are.equal(0, gaps, "the smooth-ice ocean is a SOLID sea (found " .. gaps .. " non-ice-smooth tiles)")
    assert.is_true(s.count_tiles_filtered({ name = "cindra-ice-smooth", area = box }) > 1000, "large contiguous ice ocean")
  end)

  it("keeps BOTH oceans solid on OTHER seeds (seed-independent, ci-wly)", function()
    local base = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local fd = terrain.finite_dimension()
    for _, seed in ipairs({ 111, 99999 }) do
      local mgs = base.map_gen_settings
      mgs.seed = seed
      mgs[fd.key] = fd.value
      local sname = "cindra-ocean-seed-" .. seed
      local ss = game.surfaces[sname] or game.create_surface(sname, mgs)
      ss.request_to_generate_chunks({ 0, 0 }, 15)
      ss.force_generate_chunk_requests()
      local function gaps_in(core, x1, x2)
        local g = 0
        for _, name in ipairs(terrain.tile_names()) do
          if name ~= core then g = g + ss.count_tiles_filtered({ name = name, area = { { x1, -100 }, { x2, 100 } } }) end
        end
        return g
      end
      assert.are.equal(0, gaps_in("cindra-lava-hot", -396, -204), "seed " .. seed .. ": the lava ocean is still solid")
      assert.are.equal(0, gaps_in("cindra-ice-smooth", 204, 396), "seed " .. seed .. ": the ice ocean is still solid")
    end
  end)

  -- 3. HEIGHTMAP RINGS -------------------------------------------------------------
  it("rings every lava pool with hot crust: lava never directly touches non-hot terrain", function()
    local ring_smooth, ring_other, leaks, lava_seen = 0, 0, 0, 0
    for x = -396, -135, 1 do
      for y = -150, 150, 3 do
        if LAVA[tile(x, y)] then
          lava_seen = lava_seen + 1
          for _, d in ipairs({ { 1, 0 }, { -1, 0 }, { 0, 1 }, { 0, -1 } }) do
            local n = tile(x + d[1], y + d[2])
            if not LAVA[n] then
              if n == "cindra-volcanic-smooth-stone-warm" then ring_smooth = ring_smooth + 1
              elseif HOT_CRUST[n] then ring_other = ring_other + 1
              else leaks = leaks + 1 end
            end
          end
        end
      end
    end
    assert.is_true(lava_seen > 50, "sampled a meaningful amount of lava (" .. lava_seen .. ")")
    assert.are.equal(0, leaks, "lava is always insulated by its hot-crust rings (leaks=" .. leaks .. ")")
    assert.is_true(ring_smooth >= ring_other, "the immediate ring around lava is predominantly smooth-stone-warm")
  end)

  it("rings the smooth-ice pools with cold crust: ice never directly touches middle/hot terrain", function()
    local ring, leaks, ice_seen = 0, 0, 0
    for x = 135, 396, 1 do
      for y = -150, 150, 3 do
        if tile(x, y) == "cindra-ice-smooth" then
          ice_seen = ice_seen + 1
          for _, d in ipairs({ { 1, 0 }, { -1, 0 }, { 0, 1 }, { 0, -1 } }) do
            local n = tile(x + d[1], y + d[2])
            if n ~= "cindra-ice-smooth" then
              if COLD_RING[n] then ring = ring + 1 else leaks = leaks + 1 end
            end
          end
        end
      end
    end
    assert.is_true(ice_seen > 50, "sampled a meaningful amount of smooth ice (" .. ice_seen .. ")")
    assert.are.equal(0, leaks, "smooth-ice is always insulated by its cold rings (leaks=" .. leaks .. ")")
    assert.is_true(ring > 0, "smooth-ice pools are bounded by rough-ice / snow rings")
  end)

  it("gates both oceans by the gradient: dense at the map edge, thinning toward the middle", function()
    local lava_edge = count_in(LAVA, -396, -204, -RY, RY)
    local lava_mid = count_in(LAVA, -175, -135, -RY, RY)
    assert.is_true(lava_edge > lava_mid * 3, "lava thins toward the middle (edge=" .. lava_edge .. ", mid=" .. lava_mid .. ")")
    local ice_edge = s.count_tiles_filtered({ name = "cindra-ice-smooth", area = { { 204, -RY }, { 396, RY } } })
    local ice_mid = s.count_tiles_filtered({ name = "cindra-ice-smooth", area = { { 135, -RY }, { 175, RY } } })
    assert.is_true(ice_edge > ice_mid * 3, "smooth-ice thins toward the middle (edge=" .. ice_edge .. ", mid=" .. ice_mid .. ")")
  end)

  -- 4. THREE REGIONS ---------------------------------------------------------------
  it("assigns each region its own tile family (hot / middle / cold never cross)", function()
    for _, y in ipairs({ -120, 0, 120 }) do
      for x = -195, -72, 24 do
        assert.is_true(HOT_FAMILY[tile(x, y)] == true,
          "hot slope at (" .. x .. "," .. y .. ") should be a hot-family tile, got " .. tile(x, y))
      end
      for x = -52, 52, 26 do
        assert.is_true(MIDDLE_FAMILY[tile(x, y)] == true,
          "middle at (" .. x .. "," .. y .. ") should be a middle-family tile, got " .. tile(x, y))
      end
      for x = 72, 195, 24 do
        assert.is_true(COLD_FAMILY[tile(x, y)] == true,
          "cold slope at (" .. x .. "," .. y .. ") should be a cold-family tile, got " .. tile(x, y))
      end
    end
  end)

  it("the habitable middle is a MIX of ash tiles (+ soil patches), not one flat tile", function()
    local seen = {}
    for x = -52, 52, 1 do
      for y = -120, 120, 8 do
        local n = tile(x, y)
        if MIDDLE_FAMILY[n] then seen[n] = true end
      end
    end
    local ash = 0
    for _, v in ipairs({ "cindra-volcanic-ash-dark", "cindra-volcanic-ash-light", "cindra-volcanic-ash-flats" }) do
      if seen[v] then ash = ash + 1 end
    end
    assert.is_true(ash >= 2, "the middle mixes at least two ash tiles, saw " .. ash)
    local soil = seen["cindra-volcanic-soil-dark"] or seen["cindra-volcanic-soil-light"] or seen["cindra-volcanic-ash-soil"]
    assert.is_true(soil == true, "the middle grows soil patches")
  end)

  it("draws ORGANIC (wavy) region boundaries, never raw straight lines", function()
    local first = {}
    for y = -160, 160, 10 do
      for x = 40, 120 do
        if COLD_FAMILY[tile(x, y)] and not MIDDLE_FAMILY[tile(x, y)] then first[#first + 1] = x; break end
      end
    end
    assert.is_true(#first >= 8, "sampled enough rows to judge the boundary")
    local lo, hi = first[1], first[1]
    for _, x in ipairs(first) do lo = math.min(lo, x); hi = math.max(hi, x) end
    assert.is_true(hi - lo >= 3, "the boundary wanders across rows (organic); spread=" .. tostring(hi - lo))
  end)

  -- 5. WALKABILITY -----------------------------------------------------------------
  it("makes ONLY the lava tiles impassable; smooth-ice is now walkable (ci-wly)", function()
    local function pave(name, cx, cy)
      local t = {}
      for x = cx - 4, cx + 4 do for y = cy - 4, cy + 4 do t[#t + 1] = { name = name, position = { x, y } } end end
      s.set_tiles(t, true)
    end
    local WY = 2600
    local function buildable(name)
      pave(name, 0, WY)
      return s.can_place_entity({ name = "stone-furnace", position = { 0, WY } })
    end
    assert.is_false(buildable("cindra-lava-hot"), "hot lava is impassable (unbuildable)")
    assert.is_false(buildable("cindra-lava"), "lava is impassable (unbuildable)")
    assert.is_true(buildable("cindra-ice-smooth"), "smooth-ice is now WALKABLE/buildable (you can run on it)")
    for _, walk in ipairs({ "cindra-volcanic-cracks-hot", "cindra-volcanic-ash-flats",
                            "cindra-dust-flat", "cindra-ice-rough", "cindra-snow-flat" }) do
      assert.is_true(buildable(walk), walk .. " is buildable ground")
    end
  end)

  -- 6. DAMAGE (positional descriptor) ----------------------------------------------
  it("flags the damage zones: hot ocean+inner (heat), cold inner+ocean (cold), middle safe", function()
    assert.are.equal("heat", terrain.lethal_at(-(-300)), "the hot-lava ocean is heat-lethal")
    assert.are.equal("heat", terrain.lethal_at(-(-150)), "the hot inner slope is heat-lethal")
    assert.are.equal("cold", terrain.lethal_at(-(150)), "the cold inner slope is cold-lethal")
    assert.are.equal("cold", terrain.lethal_at(-(300)), "the ice ocean is cold-lethal")
    assert.is_nil(terrain.lethal_at(-(0)), "the middle centre is safe")
    assert.is_nil(terrain.lethal_at(-(-90)), "the hot outer slope is safe")
    assert.is_nil(terrain.lethal_at(-(90)), "the cold outer slope is safe")
  end)

  -- 7. ZERO NAUVIS LEAKAGE ---------------------------------------------------------
  it("generates NO un-cloned grass and NO water anywhere (no nauvis terrain leakage)", function()
    local box = { { -396, -RY }, { 396, RY } }
    for _, n in ipairs({ "grass-1", "grass-2", "grass-3", "grass-4", "water", "deepwater" }) do
      assert.are.equal(0, s.count_tiles_filtered({ name = n, area = box }), "Cindra must generate no un-cloned " .. n)
    end
  end)

  it("paints ONLY Cindra tiles across the interior (every point is a cindra-* tile)", function()
    local cindra_set = {}
    for _, n in ipairs(terrain.tile_names()) do cindra_set[n] = true end
    for x = -390, 390, 40 do
      for y = -120, 120, 60 do
        local n = tile(x, y)
        assert.is_true(cindra_set[n] == true, "interior tile at (" .. x .. "," .. y .. ") must be a Cindra tile, got " .. n)
      end
    end
  end)

  -- 8. NATIVE RESOURCES, banded --------------------------------------------------
  local function count(name, x1, x2)
    return s.count_entities_filtered({ name = name, area = { { x1, -RY }, { x2, RY } } })
  end

  it("places stone on the middle + survivable hot margin, never on the cold side", function()
    -- stone zone perp [-60, 120.5) -> x in (-120.5, 60].
    assert.is_true(count(field.STONE, -118, 60) > 0, "stone patches on the hot ribbon")
    assert.are.equal(0, count(field.STONE, 65, 400), "no stone on the cold side (east)")
  end)

  it("places ice on the survivable cold margin, never on the hot/temperate ribbon", function()
    -- ice zone perp (-120.5, -60) -> patch CENTRES at x in (60, 120.5). Resource spots
    -- are sparse blobs, so assert on entity centres over a generous band (robust to which
    -- x a given seed's spot lands at) rather than a tight bounding-box count.
    local ice = s.find_entities_filtered({ name = field.ICE, area = { { 55, -RY }, { 130, RY } } })
    local in_band = 0
    for _, e in ipairs(ice) do if e.position.x > 60 then in_band = in_band + 1 end end
    assert.is_true(in_band > 0, "ice patches on the survivable cold margin (found " .. in_band .. ")")
    -- Purity: no ice patch CENTRED on the hot/temperate side (x <= 60), the divider.
    local warm = s.find_entities_filtered({ name = field.ICE, area = { { -400, -RY }, { 60, RY } } })
    local warm_leak = 0
    for _, e in ipairs(warm) do if e.position.x < 60 then warm_leak = warm_leak + 1 end end
    assert.are.equal(0, warm_leak, "no ice centred on the hot/temperate ribbon (found " .. warm_leak .. ")")
  end)

  it("keeps ALL harvestable fields OUT of both damage zones (ci-fb9)", function()
    -- heat zone perp >= 130 -> x <= -130; cold zone perp <= -130 -> x >= 130.
    assert.are.equal(0, count(field.STONE, -400, -131), "no stone in the heat damage zone")
    assert.are.equal(0, count(field.ICE, -400, -131), "no ice in the heat damage zone")
    assert.are.equal(0, count(field.STONE, 131, 400), "no stone in the cold damage zone")
    assert.are.equal(0, count(field.ICE, 131, 400), "no ice in the cold damage zone")
    assert.are.equal("heat", terrain.lethal_at(-(-150)), "the west scanned band really is heat-lethal")
    assert.are.equal("cold", terrain.lethal_at(-(150)), "the east scanned band really is cold-lethal")
  end)

  it("no stone/ice field ever sits on a lethal death tile (ci-4iw)", function()
    local DEATH = {
      ["cindra-ice-smooth"] = true, ["cindra-lava-hot"] = true, ["cindra-lava"] = true,
      ["cindra-volcanic-smooth-stone-warm"] = true, ["cindra-volcanic-cracks-hot"] = true,
      ["cindra-ice-rough"] = true,
    }
    local function scan(name)
      local ents = s.find_entities_filtered({ name = name, area = { { -400, -RY }, { 400, RY } } })
      local on_death = 0
      for _, e in ipairs(ents) do
        local p = e.position
        if DEATH[s.get_tile(p.x, p.y).name] then on_death = on_death + 1 end
      end
      return #ents, on_death
    end
    local n_stone, bad_stone = scan(field.STONE)
    local n_ice, bad_ice = scan(field.ICE)
    assert.is_true(n_stone > 0, "sampled real stone fields")
    assert.is_true(n_ice > 0, "sampled real ice fields")
    assert.are.equal(0, bad_stone, "no stone field on a death tile (" .. bad_stone .. " found)")
    assert.are.equal(0, bad_ice, "no ice field on a death tile (" .. bad_ice .. " found)")
  end)

  -- 8a. BOOTSTRAP + BURNED ROCKS ---------------------------------------------------
  it("scatters bootstrap rocks across the warm middle, fading before ice (ci-18n)", function()
    -- sandy rock band perp [-55, 60] -> x in [-60, 55].
    assert.is_true(s.count_entities_filtered({ name = field.ROCK, area = { { -59, -100 }, { 54, 100 } } }) > 0,
      "bootstrap rocks scatter across the warm middle")
    assert.are.equal(0, s.count_entities_filtered({ name = field.ROCK, area = { { -195, -100 }, { -70, 100 } } }),
      "no rocks out in the hot margin (masked to the middle)")
    assert.are.equal(0, s.count_entities_filtered({ name = field.ROCK, area = { { 62, -RY }, { 120, RY } } }),
      "no sandy rocks on the frosty cold edge (fades before ice, ci-18n)")
  end)

  it("scatters ice-rocks across the safe cold band, never the lethal cold zone (ci-18n)", function()
    -- ice-rock band perp (-130, -60] -> x in [60, 130).
    assert.is_true(s.count_entities_filtered({ name = field.ICE_ROCK, area = { { 62, -RY }, { 128, RY } } }) > 0,
      "ice-rocks scatter across the safe cold band")
    assert.are.equal(0, s.count_entities_filtered({ name = field.ICE_ROCK, area = { { 132, -RY }, { 400, RY } } }),
      "no ice-rocks in the lethal cold damage zone")
    local near = s.find_entities_filtered({ name = field.ICE_ROCK, area = { { -400, -RY }, { 65, RY } } })
    local warm_leak = 0
    for _, e in ipairs(near) do if e.position.x < 59 then warm_leak = warm_leak + 1 end end
    assert.are.equal(0, warm_leak, "no ice-rocks centred on the warm/temperate ribbon")
  end)

  local function count_burned(x1, x2)
    local n = 0
    for _, name in ipairs(field.burned_rock_names()) do
      n = n + s.count_entities_filtered({ name = name, area = { { x1, -RY }, { x2, RY } } })
    end
    return n
  end

  it("generates burned volcanic rocks in the hot region, clustered toward the lava (ci-qy0)", function()
    -- volcanic band perp (60,200] -> x in [-200,-60).
    assert.is_true(count_burned(-195, -65) > 0, "burned rocks generate in the hot region")
    local near_lava = count_burned(-195, -135)
    local inner = count_burned(-90, -65)
    assert.is_true(near_lava >= inner, "burned rocks cluster toward the lava (near=" .. near_lava .. ", inner=" .. inner .. ")")
  end)

  it("keeps burned rocks OUT of the middle and the cold side (ci-qy0)", function()
    assert.are.equal(0, count_burned(-55, 55), "no burned rocks in the middle")
    assert.are.equal(0, count_burned(65, 400), "no burned rocks in the cold/ice side")
  end)

  it("coal is reachable SAFELY: volcanic rocks generate in the non-lethal hot margin (ci-18n)", function()
    -- safe hot margin perp (60,130) -> x in (-130,-60]; heat damage perp >= 130 (x <= -130).
    assert.is_true(count_burned(-128, -65) > 0, "volcanic rocks (coal) generate in the SAFE hot margin")
    assert.is_nil(terrain.lethal_at(-(-65)), "the inner edge of the sampled band is safe")
    assert.is_nil(terrain.lethal_at(-(-128)), "the outer edge of the sampled band is still safe")
  end)

  -- 9. NO CLIFFS -------------------------------------------------------------------
  it("generates NO cliffs: the ribbon stays flat and traversable (ci-qqt)", function()
    assert.are.equal(0, s.count_entities_filtered({ type = "cliff", area = { { -400, -RY }, { 400, RY } } }),
      "the ribbon is cliff-free")
  end)

  -- LANDABILITY --------------------------------------------------------------------
  it("LANDABLE: the spawn tile + a base-sized pad are walkable, safe cindra ground", function()
    for x = -8, 8 do
      for y = -8, 8 do
        local n = tile(x, y)
        assert.matches("^cindra%-", n, "landing pad tile (" .. x .. "," .. y .. ") must be a cindra tile, got: " .. n)
        assert.is_true(terrain.is_walkable(n), "landing pad tile (" .. x .. "," .. y .. ") must be walkable, got: " .. n)
        assert.are.equal(0, (terrain.tile_damage(n)), "landing pad tile (" .. x .. "," .. y .. ") must be damage-free, got: " .. n)
      end
    end
  end)

  it("LANDABLE: a character dropped at spawn takes zero damage from a live tile-damage sweep", function()
    local char = s.create_entity({ name = "character", position = { 0, 0 }, force = "player" })
    assert.is_not_nil(char, "a character must be placeable at spawn")
    local before = char.health
    tile_damage.sweep(s, tile_damage.DAMAGE_INTERVAL, 200)
    assert.are.equal(before, char.health, "a character at the landing spot must take ZERO environmental damage")
    char.destroy()
  end)

  -- FINITE SURFACE + SLIDERS + MAP COLOUR -----------------------------------------
  it("bounds the REAL cindra planet surface at creation (the runtime hook works)", function()
    local live = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local mg = live.map_gen_settings
    assert.are.equal(800, mg.width, "the cindra surface is finite (800) on the perpendicular (X) axis")
    assert.is_true(mg.height == 0 or mg.height > 100000,
      "the ribbon is infinite along its long (Y) axis; got height=" .. tostring(mg.height))
  end)

  it("exposes real map-gen sliders (Stone + Ice only)", function()
    for _, n in ipairs({ "cindra-stone", "cindra-ice" }) do
      local ctrl = prototypes.autoplace_control[n]
      assert.is_not_nil(ctrl, n .. " autoplace-control exists")
      assert.are.equal("resource", ctrl.category, n .. " is a resource slider")
    end
  end)

  it("marks the danger zones on the map: hot + cold edges carry a distinct map_color (ci-4h7)", function()
    local function mc(name)
      local c = prototypes.tile[name].map_color
      assert.is_not_nil(c, name .. " has a map_color")
      local scale = (c.r > 1 or c.g > 1 or c.b > 1) and 255 or 1
      return { c.r / scale, c.g / scale, c.b / scale }
    end
    local function dist(a, b) return math.abs(a[1]-b[1]) + math.abs(a[2]-b[2]) + math.abs(a[3]-b[3]) end
    local center = mc("cindra-volcanic-ash-flats")
    local lava, ice = mc("cindra-lava-hot"), mc("cindra-ice-smooth")
    assert.is_true(dist(lava, center) > 0.5, "the hot-lava danger edge is distinct from the middle")
    assert.is_true(dist(ice, center) > 0.4, "the deep-ice danger edge is distinct from the middle")
    assert.is_true(lava[1] > lava[2] and lava[1] > lava[3], "hot lava reads red/orange on the map")
    assert.is_true(ice[3] > ice[1], "deep ice reads cold (blue) on the map")
    local vlava = prototypes.tile["lava"]
    if vlava and vlava.map_color then
      local vs = (vlava.map_color.r > 1 or vlava.map_color.g > 1 or vlava.map_color.b > 1) and 255 or 1
      assert.is_true(dist(lava, { vlava.map_color.r / vs, vlava.map_color.g / vs, vlava.map_color.b / vs }) > 0.05,
        "Cindra hot-lava has its own map_color; vanilla lava is untouched")
    end
  end)
end)
