-- Proof: Cindra is a REAL ribbon world generated by the MAP-GEN itself (ci-3yl),
-- now with the full per-zone-width hot->cold gradient (ci-a35).
--
-- No on_chunk_generated script paints or voids anything. This drives the actual
-- planet map_gen_settings on a fresh, fixed-seed surface and proves, on the default
-- vertical orientation (ribbon long axis = Y; hot-cold gradient = X, hot on the
-- LEFT / west, perp = -x):
--   1. FINITE PERPENDICULAR: the map-gen's own `width` = the SUM of the per-zone
--      widths (ci-a35) voids everything beyond the band, interior playable.
--   2. NOISE-DRIVEN TILE GRADIENT: the ground is Cindra's own `cindra-*` tiles laid
--      out hot-lava -> lava -> volcanic cracks -> jagged -> dirt -> SAND (spawn) ->
--      aquilo-dust -> rough-ice -> smooth-ice across the X axis, boundaries ORGANIC.
--   3. HOT-LAVA ALWAYS at the sunward extreme (bead ci-a35).
--   4. ZERO NAUVIS LEAKAGE: no grass, no water -- every interior tile is a Cindra tile.
--   5. NATIVE RESOURCES: stone on the ribbon/hot side, ice on the nightside, no water.
--   6. FINITE BOOTSTRAP ROCKS: scattered near spawn only, absent far down the ribbon.
--
-- The pure band geometry is proven in unit-tests/test_terrain + test_resource_field;
-- this proves it actually generates on a live surface. Band sampling scans a COLUMN
-- of rows and takes the plurality tile, so the basis-noise wiggle never flips a
-- single-point assertion.

local field = require("scripts.resource-field")
local terrain = require("scripts.terrain")

describe("cindra worldgen: a real noise-driven ribbon world (§4, §15-2; ci-3yl, ci-a35)", function()
  -- A dedicated surface cloned from the Cindra planet's own map_gen_settings (same
  -- finite width, tile bands, resource controls) at a FIXED seed, so generation is
  -- reproducible and isolated from tests that pave/trample the shared "cindra"
  -- surface. The tile bands use a fixed noise seed, so they are seed-independent;
  -- the fixed seed pins the resource patches.
  local s
  local ready = false
  local RX, RY = 140, 300

  before_each(function()
    if ready then return end
    local base = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local mgs = base.map_gen_settings
    mgs.seed = 2468
    -- The finite perpendicular bound is applied to a Cindra surface when it is
    -- created (scripts/driver.enforce_finite, since planet prototypes ignore
    -- width). This dedicated surface isn't named "cindra", so the runtime hook
    -- won't fire for it; replicate exactly what the hook does so the map-gen bands
    -- + void are generated identically.
    local fd = terrain.finite_dimension()
    mgs[fd.key] = fd.value
    s = game.surfaces["cindra-worldgen-test"] or game.create_surface("cindra-worldgen-test", mgs)
    s.request_to_generate_chunks({ 0, 0 }, 11) -- ~352-tile radius: covers the whole region
    s.force_generate_chunk_requests()
    ready = true
  end)

  local function tile(x, y) return s.get_tile(x, y).name end

  -- The plurality tile name in a column at X, scanning Y rows: robust to the
  -- basis-noise boundary wiggle (a single point can land in a neighbouring band).
  local function dominant(x, y0, y1)
    local counts = {}
    for y = y0, y1, 8 do
      local n = tile(x, y)
      counts[n] = (counts[n] or 0) + 1
    end
    local best, bestn
    for n, c in pairs(counts) do
      if not bestn or c > bestn then best, bestn = n, c end
    end
    return best
  end

  -- Half the finite extent (= sum of zone widths / 2): the +/- perp map edge.
  local HALF = terrain.layout().total / 2

  -- 1. FINITE PERPENDICULAR: width = SUM of the per-zone widths (ci-a35) ----------
  it("is finite perpendicular: width equals the SUM of the zone widths, interior playable", function()
    -- width = 240 by default -> playable X is roughly [-120, 120].
    assert.are.equal(240, terrain.finite_dimension().value, "the extent is the sum of the zone widths")
    assert.are.equal("out-of-map", tile(-(HALF + 8), 0), "sunward (west) beyond the band is void")
    assert.are.equal("out-of-map", tile(HALF + 8, 0), "nightward (east) beyond the band is void")
    -- The interior is real Cindra ground, not deleted chunks.
    assert.are_not.equal("out-of-map", tile(0, 0), "the sand centre is playable")
    assert.are_not.equal("out-of-map", tile(-100, 0), "the hot lethal margin is still land")
    assert.are_not.equal("out-of-map", tile(100, 0), "the cold margin is still land")
  end)

  -- 2. THE FULL HOT->COLD TILE GRADIENT across the X axis (perp = -x) -------------
  it("DEBUG dump gradient", function()
    local parts = {}
    for x = -119, 119, 5 do
      parts[#parts + 1] = x .. ":" .. (dominant(x, -80, 80):gsub("cindra%-", ""))
    end
    error("GRADIENT " .. table.concat(parts, " "))
  end)

  it("lays the full gradient hot-lava -> ... -> SAND (spawn) -> ... -> smooth-ice", function()
    -- Sampled at each band's centre; hot = negative x (perp = -x).
    assert.are.equal("cindra-hot-lava",   dominant(-116, -80, 80), "hot-lava at the sunward extreme")
    assert.are.equal("cindra-lava",       dominant(-104, -80, 80), "lava just inside the molten edge")
    assert.are.equal("cindra-jagged",     dominant(-59, -80, 80),  "the jagged volcanic mid-band")
    assert.are.equal("cindra-sand",       dominant(0, -80, 80),    "the temperate SAND spawn centre")
    assert.are.equal("cindra-aquilo-dust",dominant(40, -80, 80),   "the frost-dust cold margin")
    assert.are.equal("cindra-rough-ice",  dominant(72, -80, 80),   "the rough-ice cold margin")
    assert.are.equal("cindra-smooth-ice", dominant(104, -80, 80),  "smooth-ice at the nightward extreme")
  end)

  -- 3. HOT-LAVA IS ALWAYS at the sunward extreme (the bead's core fix) ------------
  it("ALWAYS generates a hot-lava layer at the very hot edge (before the void)", function()
    -- The outermost sunward playable column: it must be hot-lava on every row.
    local edge = -(HALF - 1)
    local hot_lava_rows, total = 0, 0
    for y = -120, 120, 8 do
      total = total + 1
      if tile(edge, y) == "cindra-hot-lava" then hot_lava_rows = hot_lava_rows + 1 end
    end
    assert.is_true(hot_lava_rows == total,
      "every row at the hot edge is hot-lava (" .. hot_lava_rows .. "/" .. total .. ")")
  end)

  -- The spawn lands on the safe sand, never on a lethal tile.
  it("spawns the player on safe SAND at the world centre, not a lethal tile", function()
    assert.are.equal("cindra-sand", tile(0, 0), "world (0,0) is sand")
    assert.is_nil(terrain.lethal_kind(tile(0, 0)), "the spawn tile is not lethal")
  end)

  it("draws ORGANIC (wavy) band boundaries, never raw straight lines", function()
    -- Scan the hot-lava boundary on the hot (west) side across many Y rows: the X at
    -- which the ground first becomes hot-lava (scanning outward from the centre). A
    -- straight line => identical X on every row; the basis-noise wiggle makes it VARY.
    local first = {}
    for y = -120, 120, 12 do
      for x = -60, -(HALF), -1 do
        if tile(x, y) == "cindra-hot-lava" then first[#first + 1] = x; break end
      end
    end
    assert.is_true(#first >= 8, "sampled enough rows to judge the boundary")
    local lo, hi = first[1], first[1]
    for _, x in ipairs(first) do
      if x < lo then lo = x end
      if x > hi then hi = x end
    end
    assert.is_true(hi - lo >= 3,
      "the hot-lava boundary wanders across rows (organic), not a straight line; spread=" .. tostring(hi - lo))
  end)

  -- 4. ZERO NAUVIS LEAKAGE --------------------------------------------------------
  it("generates NO grass and NO water anywhere (no nauvis terrain leakage)", function()
    local box = { { -RX, -RY }, { RX, RY } }
    for _, n in ipairs({ "grass-1", "grass-2", "grass-3", "grass-4", "water", "deepwater" }) do
      assert.are.equal(0, s.count_tiles_filtered({ name = n, area = box }),
        "Cindra must generate no " .. n)
    end
  end)

  it("paints ONLY Cindra tiles across the interior (every band is a cindra-* tile)", function()
    local cindra_set = {}
    for _, n in ipairs(terrain.tile_names()) do cindra_set[n] = true end
    for x = -115, 115, 20 do
      for y = -120, 120, 40 do
        local n = tile(x, y)
        assert.is_true(cindra_set[n] == true,
          "interior tile at (" .. x .. "," .. y .. ") must be a Cindra tile, got " .. n)
      end
    end
  end)

  -- 5. NATIVE RESOURCES, banded to the ribbon axis --------------------------------
  local function count(name, x1, x2)
    return s.count_entities_filtered({ name = name, area = { { x1, -RY }, { x2, RY } } })
  end

  it("places stone as patches on the ribbon + hot side, never deep nightward", function()
    assert.is_true(count(field.STONE, -96, 24) > 0, "stone patches in the stone band")
    assert.are.equal(0, count(field.STONE, 40, HALF), "no stone deep nightward (east)")
  end)

  it("places ice as patches on the nightside, never sunward of the safe band", function()
    assert.is_true(count(field.ICE, 30, HALF) > 0, "ice patches on the nightside (east)")
    assert.are.equal(0, count(field.ICE, -HALF, 0), "no ice sunward (west) of the safe band")
  end)

  -- 6. FINITE BOOTSTRAP ROCKS -----------------------------------------------------
  it("scatters finite bootstrap rocks near spawn only, absent far down the ribbon", function()
    -- Near spawn (inside the sand band AND the spawn disk): present.
    local near = s.count_entities_filtered({
      name = field.ROCK, area = { { -24, -100 }, { 24, 100 } } })
    assert.is_true(near > 0, "bootstrap rocks scatter around the landing centre")
    -- Far down the ribbon, past the finite spawn range: none (finite, not infinite).
    local far = s.count_entities_filtered({
      name = field.ROCK, area = { { -24, field.ROCK_SPAWN_RANGE + 20 }, { 24, RY } } })
    assert.are.equal(0, far, "no rocks beyond the finite spawn disk (rocks are finite)")
  end)

  it("bounds the REAL cindra planet surface at creation (the runtime hook works)", function()
    -- The planet prototype's width is ignored by the engine, so scripts/driver sets
    -- it (= sum of zone widths) when the surface is created. Prove the actual
    -- "cindra" surface came out finite perpendicular (width), infinite long axis.
    local live = game.surfaces["cindra"]
      or (game.planets["cindra"] and game.planets["cindra"].create_surface())
    local mg = live.map_gen_settings
    assert.are.equal(240, mg.width, "the cindra surface is finite on the perpendicular (X) axis = zone-width sum")
    assert.is_true(mg.height == 0 or mg.height > 100000,
      "the ribbon is infinite along its long (Y) axis; got height=" .. tostring(mg.height))
  end)

  it("exposes real map-gen sliders (Stone + Ice only, no standalone volatiles)", function()
    for _, n in ipairs({ "cindra-stone", "cindra-ice" }) do
      local ctrl = prototypes.autoplace_control[n]
      assert.is_not_nil(ctrl, n .. " autoplace-control exists")
      assert.are.equal("resource", ctrl.category, n .. " is a resource slider")
    end
    assert.is_nil(prototypes.autoplace_control["cindra-volatiles"],
      "the standalone volatiles resource slider is gone (volatiles come from the ice chain)")
    assert.is_nil(prototypes.entity["cindra-volatiles"],
      "there is no standalone volatiles resource entity")
    -- The volatiles ITEM survives (a science-pack input from the ice chain).
    assert.is_not_nil(prototypes.item["cindra-volatiles"], "the volatiles item survives")
  end)
end)
